/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, Schema } from '../schema.js';
import {
  CreateSplitRequest,
  createSplitRequestSchema,
} from './createSplitRequest.js';

export interface CreateSubscriptionSplitRequest {
  /** Defines if the split is enabled */
  enabled: boolean;
  /** Split */
  rules: CreateSplitRequest[];
}

export const createSubscriptionSplitRequestSchema: Schema<CreateSubscriptionSplitRequest> = lazy(
  () =>
    object({
      enabled: ['enabled', boolean()],
      rules: ['rules', array(createSplitRequestSchema)],
    })
);
