/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  CreatePhoneRequest,
  createPhoneRequestSchema,
} from './createPhoneRequest';

export interface CreatePhonesRequest {
  homePhone?: CreatePhoneRequest;
  mobilePhone?: CreatePhoneRequest;
}

export const createPhonesRequestSchema: Schema<CreatePhonesRequest> = object({
  homePhone: ['home_phone', optional(lazy(() => createPhoneRequestSchema))],
  mobilePhone: ['mobile_phone', optional(lazy(() => createPhoneRequestSchema))],
});
