/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, Schema, string } from '../schema';
import {
  CreateRegisterInformationAddressRequest,
  createRegisterInformationAddressRequestSchema,
} from './createRegisterInformationAddressRequest';
import {
  CreateRegisterInformationPhoneRequest,
  createRegisterInformationPhoneRequestSchema,
} from './createRegisterInformationPhoneRequest';

/** Managing Partner Request */
export interface CreateManagingPartnerRequest {
  name: string;
  email: string;
  document: string;
  motherName: string;
  birthdate: string;
  monthlyIncome: string;
  professionalOccupation: string;
  selfDeclaredLegalRepresentative: boolean;
  address: CreateRegisterInformationAddressRequest;
  phoneNumbers: CreateRegisterInformationPhoneRequest[];
}

export const createManagingPartnerRequestSchema: Schema<CreateManagingPartnerRequest> = object(
  {
    name: ['name', string()],
    email: ['email', string()],
    document: ['document', string()],
    motherName: ['mother_name', string()],
    birthdate: ['birthdate', string()],
    monthlyIncome: ['monthly_income', string()],
    professionalOccupation: ['professional_occupation', string()],
    selfDeclaredLegalRepresentative: [
      'self_declared_legal_representative',
      boolean(),
    ],
    address: [
      'address',
      lazy(() => createRegisterInformationAddressRequestSchema),
    ],
    phoneNumbers: [
      'phone_numbers',
      array(lazy(() => createRegisterInformationPhoneRequestSchema)),
    ],
  }
);
