/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

/** The Split Options Request */
export interface CreateSplitOptionsRequest {
  /** Liable options */
  liable?: boolean;
  /** Charge processing fee */
  chargeProcessingFee?: boolean;
  chargeRemainderFee?: boolean;
}

export const createSplitOptionsRequestSchema: Schema<CreateSplitOptionsRequest> = object(
  {
    liable: ['liable', optional(boolean())],
    chargeProcessingFee: ['charge_processing_fee', optional(boolean())],
    chargeRemainderFee: ['charge_remainder_fee', optional(boolean())],
  }
);
