/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, object, optional, Schema, string } from '../schema';
import {
  CreateBankAccountRequest,
  createBankAccountRequestSchema,
} from './createBankAccountRequest';
import {
  CreateTransferSettingsRequest,
  createTransferSettingsRequestSchema,
} from './createTransferSettingsRequest';

/** Request for creating a recipient */
export interface CreateRecipientRequest {
  /** Recipient name */
  name: string;
  /** Recipient email */
  email: string;
  /** Recipient description */
  description: string;
  /** Recipient document number */
  document: string;
  /** Recipient type */
  type: string;
  /** Bank account */
  defaultBankAccount: CreateBankAccountRequest;
  /** Metadata */
  metadata: Record<string, string>;
  /** Receiver Transfer Information */
  transferSettings?: CreateTransferSettingsRequest;
  /** Recipient code */
  code: string;
  /** Payment mode */
  paymentMode: string;
}

export const createRecipientRequestSchema: Schema<CreateRecipientRequest> = object(
  {
    name: ['name', string()],
    email: ['email', string()],
    description: ['description', string()],
    document: ['document', string()],
    type: ['type', string()],
    defaultBankAccount: [
      'default_bank_account',
      lazy(() => createBankAccountRequestSchema),
    ],
    metadata: ['metadata', dict(string())],
    transferSettings: [
      'transfer_settings',
      optional(lazy(() => createTransferSettingsRequestSchema)),
    ],
    code: ['code', string()],
    paymentMode: ['payment_mode', string()],
  }
);
