/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  CreateCardTokenRequest,
  createCardTokenRequestSchema,
} from './createCardTokenRequest.js';

/** Token data */
export interface CreateTokenRequest {
  /** Token type */
  type: string;
  /** Card data */
  card: CreateCardTokenRequest;
}

export const createTokenRequestSchema: Schema<CreateTokenRequest> = lazy(() =>
  object({
    type: ['type', string()],
    card: ['card', createCardTokenRequestSchema],
  })
);
