/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Request for creating an order item */
export interface CreateOrderItemRequest {
  /** Amount */
  amount: number;
  /** Description */
  description: string;
  /** Quantity */
  quantity: number;
  /** Category */
  category: string;
  /** The item code passed by the client */
  code?: string;
}

export const createOrderItemRequestSchema: Schema<CreateOrderItemRequest> = object(
  {
    amount: ['amount', number()],
    description: ['description', string()],
    quantity: ['quantity', number()],
    category: ['category', string()],
    code: ['code', optional(string())],
  }
);
