/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import {
  CreateApplePayHeaderRequest,
  createApplePayHeaderRequestSchema,
} from './createApplePayHeaderRequest';

/** The ApplePay Token Payment Request */
export interface CreateApplePayRequest {
  /** The token version */
  version: string;
  /** The cryptography data */
  data: string;
  /** The ApplePay header request */
  header: CreateApplePayHeaderRequest;
  /** Detached PKCS #7 signature, Base64 encoded as string */
  signature: string;
  /** ApplePay Merchant identifier */
  merchantIdentifier: string;
}

export const createApplePayRequestSchema: Schema<CreateApplePayRequest> = object(
  {
    version: ['version', string()],
    data: ['data', string()],
    header: ['header', lazy(() => createApplePayHeaderRequestSchema)],
    signature: ['signature', string()],
    merchantIdentifier: ['merchant_identifier', string()],
  }
);
