/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  CreateManagingPartnerRequest,
  createManagingPartnerRequestSchema,
} from './createManagingPartnerRequest';
import {
  CreateRegisterInformationAddressRequest,
  createRegisterInformationAddressRequestSchema,
} from './createRegisterInformationAddressRequest';
import { CreateRegisterInformationBaseRequest } from './createRegisterInformationBaseRequest';
import { createRegisterInformationPhoneRequestSchema } from './createRegisterInformationPhoneRequest';

export interface CreateRegisterInformationCorporationRequest extends CreateRegisterInformationBaseRequest {
  companyName: string;
  tradingName: string;
  annualRevenue: bigint;
  corporationType?: string | null;
  foundingDate?: string | null;
  cnae?: string | null;
  managingPartners: CreateManagingPartnerRequest[];
  mainAddress: CreateRegisterInformationAddressRequest;
}

export const createRegisterInformationCorporationRequestSchema: Schema<CreateRegisterInformationCorporationRequest> = object(
  {
    companyName: ['company_name', string()],
    tradingName: ['trading_name', string()],
    annualRevenue: ['annual_revenue', bigint()],
    corporationType: ['corporation_type', optional(nullable(string()))],
    foundingDate: ['founding_date', optional(nullable(string()))],
    cnae: ['cnae', optional(nullable(string()))],
    managingPartners: [
      'managing_partners',
      array(lazy(() => createManagingPartnerRequestSchema)),
    ],
    mainAddress: [
      'main_address',
      lazy(() => createRegisterInformationAddressRequestSchema),
    ],
    email: ['email', string()],
    document: ['document', string()],
    type: ['type', string()],
    siteUrl: ['site_url', optional(nullable(string()))],
    phoneNumbers: [
      'phone_numbers',
      array(lazy(() => createRegisterInformationPhoneRequestSchema)),
    ],
  }
);
