/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  PixAdditionalInformation,
  pixAdditionalInformationSchema,
} from './pixAdditionalInformation';

/** Contains information to create a pix payment */
export interface CreatePixPaymentRequest {
  /** Datetime when pix payment will expire */
  expiresAt?: string;
  /** Seconds until pix payment expires */
  expiresIn?: number;
  /** Pix additional information */
  additionalInformation?: PixAdditionalInformation[];
}

export const createPixPaymentRequestSchema: Schema<CreatePixPaymentRequest> = object(
  {
    expiresAt: ['expires_at', optional(string())],
    expiresIn: ['expires_in', optional(number())],
    additionalInformation: [
      'additional_information',
      optional(array(lazy(() => pixAdditionalInformationSchema))),
    ],
  }
);
