/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  CreateRegisterInformationAddressRequest,
  createRegisterInformationAddressRequestSchema,
} from './createRegisterInformationAddressRequest.js';
import {
  CreateRegisterInformationPhoneRequest,
  createRegisterInformationPhoneRequestSchema,
} from './createRegisterInformationPhoneRequest.js';

/** Managing Partner Request */
export interface CreateManagingPartnerRequest {
  name: string;
  email: string;
  document: string;
  motherName?: string | null;
  birthdate: string;
  monthlyIncome: bigint;
  professionalOccupation: string;
  selfDeclaredLegalRepresentative: boolean;
  address: CreateRegisterInformationAddressRequest;
  phoneNumbers: CreateRegisterInformationPhoneRequest[];
}

export const createManagingPartnerRequestSchema: Schema<CreateManagingPartnerRequest> = lazy(
  () =>
    object({
      name: ['name', string()],
      email: ['email', string()],
      document: ['document', string()],
      motherName: ['mother_name', optional(nullable(string()))],
      birthdate: ['birthdate', string()],
      monthlyIncome: ['monthly_income', bigint()],
      professionalOccupation: ['professional_occupation', string()],
      selfDeclaredLegalRepresentative: [
        'self_declared_legal_representative',
        boolean(),
      ],
      address: ['address', createRegisterInformationAddressRequestSchema],
      phoneNumbers: [
        'phone_numbers',
        array(createRegisterInformationPhoneRequestSchema),
      ],
    })
);
