/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  CreateClearSaleRequest,
  createClearSaleRequestSchema,
} from './createClearSaleRequest.js';

export interface CreateAntifraudRequest {
  type: string;
  clearsale: CreateClearSaleRequest;
}

export const createAntifraudRequestSchema: Schema<CreateAntifraudRequest> = lazy(
  () =>
    object({
      type: ['type', string()],
      clearsale: ['clearsale', createClearSaleRequestSchema],
    })
);
