/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CreateEmvDataTlvDecryptRequest {
  /** Emv tag */
  tag: string;
  /** Emv lenght */
  lenght: string;
  /** Emv value */
  value: string;
}

export const createEmvDataTlvDecryptRequestSchema: Schema<CreateEmvDataTlvDecryptRequest> = object(
  {
    tag: ['tag', string()],
    lenght: ['lenght', string()],
    value: ['value', string()],
  }
);
