/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, number, object, Schema, string } from '../schema';

/** Request for creating a transfer */
export interface CreateTransferRequest {
  /** Transfer amount */
  amount: number;
  /** Metadata */
  metadata: Record<string, string>;
}

export const createTransferRequestSchema: Schema<CreateTransferRequest> = object(
  { amount: ['amount', number()], metadata: ['metadata', dict(string())] }
);
