/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  CreateRegisterInformationPhoneRequest,
  createRegisterInformationPhoneRequestSchema,
} from './createRegisterInformationPhoneRequest';

/** Request object for RegisterInformation. */
export interface CreateRegisterInformationBaseRequest {
  email: string;
  document: string;
  /** "individual" ou "corporation" */
  type: string;
  siteUrl?: string | null;
  phoneNumbers: CreateRegisterInformationPhoneRequest[];
}

export const createRegisterInformationBaseRequestSchema: Schema<CreateRegisterInformationBaseRequest> = object(
  {
    email: ['email', string()],
    document: ['document', string()],
    type: ['type', string()],
    siteUrl: ['site_url', optional(nullable(string()))],
    phoneNumbers: [
      'phone_numbers',
      array(lazy(() => createRegisterInformationPhoneRequestSchema)),
    ],
  }
);
