/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CreateTransactionReportFileRequest {
  name: string;
  startAt?: string;
  endAt?: string;
}

export const createTransactionReportFileRequestSchema: Schema<CreateTransactionReportFileRequest> = object(
  {
    name: ['name', string()],
    startAt: ['start_at', optional(string())],
    endAt: ['end_at', optional(string())],
  }
);
