/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  CreateThreeDSecureRequest,
  createThreeDSecureRequestSchema,
} from './createThreeDSecureRequest.js';

/** The payment authentication request */
export interface CreatePaymentAuthenticationRequest {
  /** The Authentication type */
  type: string;
  /** The 3D-S authentication object */
  threedSecure: CreateThreeDSecureRequest;
}

export const createPaymentAuthenticationRequestSchema: Schema<CreatePaymentAuthenticationRequest> = lazy(
  () =>
    object({
      type: ['type', string()],
      threedSecure: ['threed_secure', createThreeDSecureRequestSchema],
    })
);
