/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema';

/** Request for canceling a subscription */
export interface CreateCancelSubscriptionRequest {
  /** Indicates if the pending invoices must also be canceled. */
  cancelPendingInvoices: boolean;
}

export const createCancelSubscriptionRequestSchema: Schema<CreateCancelSubscriptionRequest> = object(
  { cancelPendingInvoices: ['cancel_pending_invoices', boolean()] }
);
