/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

/** Request for creating a new Access Token */
export interface CreateAccessTokenRequest {
  /** Minutes to expire the token */
  expiresIn?: number;
}

export const createAccessTokenRequestSchema: Schema<CreateAccessTokenRequest> = object(
  { expiresIn: ['expires_in', optional(number())] }
);
