/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  CreatePriceBracketRequest,
  createPriceBracketRequestSchema,
} from './createPriceBracketRequest';

/** Request for creating a pricing scheme */
export interface CreatePricingSchemeRequest {
  /** Scheme type */
  schemeType: string;
  /** Price brackets */
  priceBrackets?: CreatePriceBracketRequest[];
  /** Price */
  price?: number;
  /** Minimum price */
  minimumPrice?: number;
  /** percentual value used in pricing_scheme Percent */
  percentage?: number;
}

export const createPricingSchemeRequestSchema: Schema<CreatePricingSchemeRequest> = object(
  {
    schemeType: ['scheme_type', string()],
    priceBrackets: [
      'price_brackets',
      optional(array(lazy(() => createPriceBracketRequestSchema))),
    ],
    price: ['price', optional(number())],
    minimumPrice: ['minimum_price', optional(number())],
    percentage: ['percentage', optional(number())],
  }
);
