/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

/** Card token data */
export interface CreateCardTokenRequest {
  /** Credit card number */
  number: string;
  /** Holder name, as written on the card */
  holderName: string;
  /** The expiration month */
  expMonth: number;
  /** The expiration year, that can be informed with 2 or 4 digits */
  expYear: number;
  /** The card's security code */
  cvv: string;
  /** Card brand */
  brand: string;
  label: string;
}

export const createCardTokenRequestSchema: Schema<CreateCardTokenRequest> = object(
  {
    number: ['number', string()],
    holderName: ['holder_name', string()],
    expMonth: ['exp_month', number()],
    expYear: ['exp_year', number()],
    cvv: ['cvv', string()],
    brand: ['brand', string()],
    label: ['label', string()],
  }
);
