/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, number, object, optional, Schema } from '../schema.js';
import {
  CreateFineRequest,
  createFineRequestSchema,
} from './createFineRequest.js';
import {
  CreateInterestRequest,
  createInterestRequestSchema,
} from './createInterestRequest.js';

/** Information about fines and interest on the "boleto" used from payment */
export interface CreateSubscriptionBoletoRequest {
  interest?: CreateInterestRequest;
  fine?: CreateFineRequest;
  maxDaysToPayPastDue?: number | null;
}

export const createSubscriptionBoletoRequestSchema: Schema<CreateSubscriptionBoletoRequest> = lazy(
  () =>
    object({
      interest: ['interest', optional(createInterestRequestSchema)],
      fine: ['fine', optional(createFineRequestSchema)],
      maxDaysToPayPastDue: [
        'max_days_to_pay_past_due',
        optional(nullable(number())),
      ],
    })
);
