/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  PixAdditionalInformation,
  pixAdditionalInformationSchema,
} from './pixAdditionalInformation';

/** Checkout pix payment request */
export interface CreateCheckoutPixPaymentRequest {
  /** Expires at */
  expiresAt?: string;
  /** Expires in */
  expiresIn?: number;
  /** Additional information */
  additionalInformation?: PixAdditionalInformation[];
}

export const createCheckoutPixPaymentRequestSchema: Schema<CreateCheckoutPixPaymentRequest> = object(
  {
    expiresAt: ['expires_at', optional(string())],
    expiresIn: ['expires_in', optional(number())],
    additionalInformation: [
      'additional_information',
      optional(array(lazy(() => pixAdditionalInformationSchema))),
    ],
  }
);
