/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  CreateEmvDataDukptDecryptRequest,
  createEmvDataDukptDecryptRequestSchema,
} from './createEmvDataDukptDecryptRequest';
import {
  CreateEmvDataTlvDecryptRequest,
  createEmvDataTlvDecryptRequestSchema,
} from './createEmvDataTlvDecryptRequest';

export interface CreateEmvDataDecryptRequest {
  /** Emv Decrypt cipher type */
  cipher: string;
  /** Dukpt data request */
  dukpt?: CreateEmvDataDukptDecryptRequest;
  /** Encrypted tags list */
  tags: CreateEmvDataTlvDecryptRequest[];
}

export const createEmvDataDecryptRequestSchema: Schema<CreateEmvDataDecryptRequest> = object(
  {
    cipher: ['cipher', string()],
    dukpt: [
      'dukpt',
      optional(lazy(() => createEmvDataDukptDecryptRequestSchema)),
    ],
    tags: ['tags', array(lazy(() => createEmvDataTlvDecryptRequestSchema))],
  }
);
