/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import {
  CreateGooglePayIntermediateSigningKeyRequest,
  createGooglePayIntermediateSigningKeyRequestSchema,
} from './createGooglePayIntermediateSigningKeyRequest';

/** The GooglePay Token Payment Request */
export interface CreateGooglePayRequest {
  /** Informação sobre a versão do token. Único valor aceito é EC_v2 */
  version: string;
  /** Dados de pagamento criptografados. Corresponde ao encryptedMessage do token Google. */
  data: string;
  /** The GooglePay intermediate signing key request */
  intermediateSigningKey: CreateGooglePayIntermediateSigningKeyRequest;
  /** Assinatura dos dados de pagamento. Verifica se a origem da mensagem é o Google. Corresponde ao signature do token Google. */
  signature: string;
  signedMessage: string;
}

export const createGooglePayRequestSchema: Schema<CreateGooglePayRequest> = object(
  {
    version: ['version', string()],
    data: ['data', string()],
    intermediateSigningKey: [
      'intermediate_signing_key',
      lazy(() => createGooglePayIntermediateSigningKeyRequestSchema),
    ],
    signature: ['signature', string()],
    signedMessage: ['signed_message', string()],
  }
);
