/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Bank Account */
export interface CreateBankAccountRefundingDTO {
  /** Nome/razão social do favorecido */
  holderName: string;
  /** Tipo de titular (pessoa física ou jurídica) */
  holderType: string;
  /** CPF ou CNPJ do favorecido */
  holderDocument: string;
  /** Dígitos que identificam cada banco. */
  bank: string;
  /** Número da agência bancária */
  branchNumber: string;
  /** Dígito da agência bancária */
  branchCheckDigit: string;
  /** Número da conta */
  accountNumber: string;
  /** Dígito verificador da conta */
  accountCheckDigit: string;
  /** Tipo de conta */
  type: string;
}

export const createBankAccountRefundingDTOSchema: Schema<CreateBankAccountRefundingDTO> = object(
  {
    holderName: ['holder_name', string()],
    holderType: ['holder_type', string()],
    holderDocument: ['holder_document', string()],
    bank: ['bank', string()],
    branchNumber: ['branch_number', string()],
    branchCheckDigit: ['branch_check_digit', string()],
    accountNumber: ['account_number', string()],
    accountCheckDigit: ['account_check_digit', string()],
    type: ['type', string()],
  }
);
