/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, nullable, object, optional, Schema, string } from '../schema';

/** Request for creating a bank account */
export interface CreateBankAccountRequest {
  /** Bank account holder name */
  holderName: string;
  /** Bank account holder type */
  holderType: string;
  /** Bank account holder document */
  holderDocument: string;
  /** Bank */
  bank: string;
  /** Branch number */
  branchNumber: string;
  /** Branch check digit */
  branchCheckDigit?: string | null;
  /** Account number */
  accountNumber: string;
  /** Account check digit */
  accountCheckDigit: string;
  /** Bank account type */
  type: string;
  /** Metadata */
  metadata: Record<string, string>;
  /** Pix key */
  pixKey?: string | null;
}

export const createBankAccountRequestSchema: Schema<CreateBankAccountRequest> = object(
  {
    holderName: ['holder_name', string()],
    holderType: ['holder_type', string()],
    holderDocument: ['holder_document', string()],
    bank: ['bank', string()],
    branchNumber: ['branch_number', string()],
    branchCheckDigit: ['branch_check_digit', optional(nullable(string()))],
    accountNumber: ['account_number', string()],
    accountCheckDigit: ['account_check_digit', string()],
    type: ['type', string()],
    metadata: ['metadata', dict(string())],
    pixKey: ['pix_key', optional(nullable(string()))],
  }
);
