/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, nullable, object, optional, Schema, string } from '../schema';

/** Request for creating a new Address */
export interface CreateAddressRequest {
  /** Street */
  street: string;
  /** Number */
  number: string;
  /** The zip code containing only numbers. No special characters or spaces. */
  zipCode: string;
  /** Neighborhood */
  neighborhood: string;
  /** City */
  city: string;
  /** State */
  state: string;
  /** Country. Must be entered using ISO 3166-1 alpha-2 format. See https://pt.wikipedia.org/wiki/ISO_3166-1_alfa-2 */
  country: string;
  /** Complement */
  complement: string;
  /** Metadata */
  metadata?: Record<string, string> | null;
  /** Line 1 for address */
  line1: string;
  /** Line 2 for address */
  line2: string;
}

export const createAddressRequestSchema: Schema<CreateAddressRequest> = object({
  street: ['street', string()],
  number: ['number', string()],
  zipCode: ['zip_code', string()],
  neighborhood: ['neighborhood', string()],
  city: ['city', string()],
  state: ['state', string()],
  country: ['country', string()],
  complement: ['complement', string()],
  metadata: ['metadata', optional(nullable(dict(string())))],
  line1: ['line_1', string()],
  line2: ['line_2', string()],
});
