/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface CreateClearSaleRequest {
  customSla: number;
}

export const createClearSaleRequestSchema: Schema<CreateClearSaleRequest> = object(
  { customSla: ['custom_sla', number()] }
);
