/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  CreateBankTransferPaymentRequest,
  createBankTransferPaymentRequestSchema,
} from './createBankTransferPaymentRequest.js';
import {
  CreateBoletoPaymentRequest,
  createBoletoPaymentRequestSchema,
} from './createBoletoPaymentRequest.js';
import {
  CreateCashPaymentRequest,
  createCashPaymentRequestSchema,
} from './createCashPaymentRequest.js';
import {
  CreateCheckoutPaymentRequest,
  createCheckoutPaymentRequestSchema,
} from './createCheckoutPaymentRequest.js';
import {
  CreateCreditCardPaymentRequest,
  createCreditCardPaymentRequestSchema,
} from './createCreditCardPaymentRequest.js';
import {
  CreateCustomerRequest,
  createCustomerRequestSchema,
} from './createCustomerRequest.js';
import {
  CreateDebitCardPaymentRequest,
  createDebitCardPaymentRequestSchema,
} from './createDebitCardPaymentRequest.js';
import {
  CreatePixPaymentRequest,
  createPixPaymentRequestSchema,
} from './createPixPaymentRequest.js';
import {
  CreatePrivateLabelPaymentRequest,
  createPrivateLabelPaymentRequestSchema,
} from './createPrivateLabelPaymentRequest.js';
import {
  CreateSplitRequest,
  createSplitRequestSchema,
} from './createSplitRequest.js';
import {
  CreateVoucherPaymentRequest,
  createVoucherPaymentRequestSchema,
} from './createVoucherPaymentRequest.js';

/** Payment data */
export interface CreatePaymentRequest {
  /** Payment method */
  paymentMethod: string;
  /** Settings for credit card payment */
  creditCard?: CreateCreditCardPaymentRequest;
  /** Settings for debit card payment */
  debitCard?: CreateDebitCardPaymentRequest;
  /** Settings for boleto payment */
  boleto?: CreateBoletoPaymentRequest;
  /** Currency. Must be informed using 3 characters */
  currency?: string;
  /** Settings for voucher payment */
  voucher?: CreateVoucherPaymentRequest;
  /** Splits */
  split?: CreateSplitRequest[];
  /** Settings for bank transfer payment */
  bankTransfer?: CreateBankTransferPaymentRequest;
  /** Gateway affiliation code */
  gatewayAffiliationId?: string;
  /** The amount of the payment, in cents */
  amount?: number;
  /** Settings for checkout payment */
  checkout?: CreateCheckoutPaymentRequest;
  /** Customer Id */
  customerId?: string;
  /** Customer */
  customer?: CreateCustomerRequest;
  /** Metadata */
  metadata?: Record<string, string>;
  /** Settings for cash payment */
  cash?: CreateCashPaymentRequest;
  /** Settings for private label payment */
  privateLabel?: CreatePrivateLabelPaymentRequest;
  /** Settings for pix payment */
  pix?: CreatePixPaymentRequest;
}

export const createPaymentRequestSchema: Schema<CreatePaymentRequest> = lazy(
  () =>
    object({
      paymentMethod: ['payment_method', string()],
      creditCard: [
        'credit_card',
        optional(createCreditCardPaymentRequestSchema),
      ],
      debitCard: ['debit_card', optional(createDebitCardPaymentRequestSchema)],
      boleto: ['boleto', optional(createBoletoPaymentRequestSchema)],
      currency: ['currency', optional(string())],
      voucher: ['voucher', optional(createVoucherPaymentRequestSchema)],
      split: ['split', optional(array(createSplitRequestSchema))],
      bankTransfer: [
        'bank_transfer',
        optional(createBankTransferPaymentRequestSchema),
      ],
      gatewayAffiliationId: ['gateway_affiliation_id', optional(string())],
      amount: ['amount', optional(number())],
      checkout: ['checkout', optional(createCheckoutPaymentRequestSchema)],
      customerId: ['customer_id', optional(string())],
      customer: ['customer', optional(createCustomerRequestSchema)],
      metadata: ['metadata', optional(dict(string()))],
      cash: ['cash', optional(createCashPaymentRequestSchema)],
      privateLabel: [
        'private_label',
        optional(createPrivateLabelPaymentRequestSchema),
      ],
      pix: ['pix', optional(createPixPaymentRequestSchema)],
    })
);
