/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, Schema, string } from '../schema';

/** Request for creating a new Invoice */
export interface CreateInvoiceRequest {
  /** Metadata */
  metadata: Record<string, string>;
}

export const createInvoiceRequestSchema: Schema<CreateInvoiceRequest> = object({
  metadata: ['metadata', dict(string())],
});
