/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  CreateAddressRequest,
  createAddressRequestSchema,
} from './createAddressRequest.js';
import {
  CreatePhoneRequest,
  createPhoneRequestSchema,
} from './createPhoneRequest.js';

/** SubMerchant */
export interface CreateSubMerchantRequest {
  /** Payment Facilitator Code */
  paymentFacilitatorCode: string;
  /** Code */
  code: string;
  /** Name */
  name: string;
  /** Merchant Category Code */
  merchantCategoryCode: string;
  /** Document number. Only numbers, no special characters. */
  document: string;
  /** Document type. Can be either 'individual' or 'company' */
  type: string;
  /** Phone */
  phone: CreatePhoneRequest;
  /** Address */
  address: CreateAddressRequest;
  /** Legal name */
  legalName: string;
  /** Site Url */
  siteUrl: string;
}

export const createSubMerchantRequestSchema: Schema<CreateSubMerchantRequest> = lazy(
  () =>
    object({
      paymentFacilitatorCode: ['payment_facilitator_code', string()],
      code: ['code', string()],
      name: ['name', string()],
      merchantCategoryCode: ['merchant_category_code', string()],
      document: ['document', string()],
      type: ['type', string()],
      phone: ['phone', createPhoneRequestSchema],
      address: ['address', createAddressRequestSchema],
      legalName: ['legal_name', string()],
      siteUrl: ['site_url', string()],
    })
);
