/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Request for creating a device */
export interface CreateDeviceRequest {
  /** Device's platform */
  platform?: string;
}

export const createDeviceRequestSchema: Schema<CreateDeviceRequest> = object({
  platform: ['platform', optional(string())],
});
