/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** The GooglePay Intermediate Signing Key Request */
export interface CreateGooglePayIntermediateSigningKeyRequest {
  /** Uma mensagem codificada em Base64 com a descrição de pagamento da chave. */
  signedKey: string;
  /** Verifica se a origem da chave de assinatura intermediária é o Google. É codificada em Base64 e criada usando o ECDSA. */
  signatures: string[];
}

export const createGooglePayIntermediateSigningKeyRequestSchema: Schema<CreateGooglePayIntermediateSigningKeyRequest> = object(
  {
    signedKey: ['signed_key', string()],
    signatures: ['signatures', array(string())],
  }
);
