/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema.js';
import {
  CreateGooglePayRequest,
  createGooglePayRequestSchema,
} from './createGooglePayRequest.js';

export interface CreateCardPayloadRequest {
  type?: string | null;
  googlePay?: CreateGooglePayRequest | null;
}

export const createCardPayloadRequestSchema: Schema<CreateCardPayloadRequest> = lazy(
  () =>
    object({
      type: ['type', optional(nullable(string()))],
      googlePay: [
        'google_pay',
        optional(nullable(createGooglePayRequestSchema)),
      ],
    })
);
