/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

/** Request object for PaymentOrigin */
export interface CreatePaymentOriginRequest {
  brandId?: string | null;
  chargeId?: string | null;
}

export const createPaymentOriginRequestSchema: Schema<CreatePaymentOriginRequest> = object(
  {
    brandId: ['brand_id', optional(nullable(string()))],
    chargeId: ['charge_id', optional(nullable(string()))],
  }
);
