/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** The GooglePay header request */
export interface CreateGooglePayHeaderRequest {
  /** X.509 encoded key bytes, Base64 encoded as a string */
  ephemeralPublicKey: string;
}

export const createGooglePayHeaderRequestSchema: Schema<CreateGooglePayHeaderRequest> = object(
  { ephemeralPublicKey: ['ephemeral_public_key', string()] }
);
