/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  CreateCardPaymentContactlessPOIRequest,
  createCardPaymentContactlessPOIRequestSchema,
} from './createCardPaymentContactlessPOIRequest';
import {
  CreateEmvDataDecryptRequest,
  createEmvDataDecryptRequestSchema,
} from './createEmvDataDecryptRequest';

export interface CreateEmvDecryptRequest {
  iccData: string;
  cardSequenceNumber: string;
  data: CreateEmvDataDecryptRequest;
  poi?: CreateCardPaymentContactlessPOIRequest;
}

export const createEmvDecryptRequestSchema: Schema<CreateEmvDecryptRequest> = object(
  {
    iccData: ['icc_data', string()],
    cardSequenceNumber: ['card_sequence_number', string()],
    data: ['data', lazy(() => createEmvDataDecryptRequestSchema)],
    poi: [
      'poi',
      optional(lazy(() => createCardPaymentContactlessPOIRequestSchema)),
    ],
  }
);
