/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  CreateAntifraudRequest,
  createAntifraudRequestSchema,
} from './createAntifraudRequest';
import {
  CreateCustomerRequest,
  createCustomerRequestSchema,
} from './createCustomerRequest';
import {
  CreatePaymentRequest,
  createPaymentRequestSchema,
} from './createPaymentRequest';

/** Request for creating a new charge */
export interface CreateChargeRequest {
  /** Code */
  code: string;
  /** The amount of the charge, in cents */
  amount: number;
  /** The customer's id */
  customerId: string;
  /** Customer data */
  customer: CreateCustomerRequest;
  /** Payment data */
  payment: CreatePaymentRequest;
  /** Metadata */
  metadata: Record<string, string>;
  /** The charge due date */
  dueAt?: string;
  antifraud: CreateAntifraudRequest;
  /** Order Id */
  orderId: string;
}

export const createChargeRequestSchema: Schema<CreateChargeRequest> = object({
  code: ['code', string()],
  amount: ['amount', number()],
  customerId: ['customer_id', string()],
  customer: ['customer', lazy(() => createCustomerRequestSchema)],
  payment: ['payment', lazy(() => createPaymentRequestSchema)],
  metadata: ['metadata', dict(string())],
  dueAt: ['due_at', optional(string())],
  antifraud: ['antifraud', lazy(() => createAntifraudRequestSchema)],
  orderId: ['order_id', string()],
});
