/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

/** Request for creating an anticipation */
export interface CreateAnticipationRequest {
  /** Amount requested for the anticipation */
  amount: number;
  /** Timeframe */
  timeframe: string;
  /** Payment date */
  paymentDate: string;
}

export const createAnticipationRequestSchema: Schema<CreateAnticipationRequest> = object(
  {
    amount: ['amount', number()],
    timeframe: ['timeframe', string()],
    paymentDate: ['payment_date', string()],
  }
);
