/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  CreateCheckoutCardInstallmentOptionRequest,
  createCheckoutCardInstallmentOptionRequestSchema,
} from './createCheckoutCardInstallmentOptionRequest.js';
import {
  CreatePaymentAuthenticationRequest,
  createPaymentAuthenticationRequestSchema,
} from './createPaymentAuthenticationRequest.js';

/** Checkout card payment request */
export interface CreateCheckoutCreditCardPaymentRequest {
  /** Card invoice text descriptor */
  statementDescriptor?: string;
  /** Payment installment options */
  installments?: CreateCheckoutCardInstallmentOptionRequest[];
  /** Creates payment authentication */
  authentication?: CreatePaymentAuthenticationRequest;
  /** Authorize and capture? */
  capture?: boolean;
}

export const createCheckoutCreditCardPaymentRequestSchema: Schema<CreateCheckoutCreditCardPaymentRequest> = lazy(
  () =>
    object({
      statementDescriptor: ['statement_descriptor', optional(string())],
      installments: [
        'installments',
        optional(array(createCheckoutCardInstallmentOptionRequestSchema)),
      ],
      authentication: [
        'authentication',
        optional(createPaymentAuthenticationRequestSchema),
      ],
      capture: ['capture', optional(boolean())],
    })
);
