/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  CreateCardPaymentContactlessPOIRequest,
  createCardPaymentContactlessPOIRequestSchema,
} from './createCardPaymentContactlessPOIRequest.js';
import {
  CreateEmvDataDecryptRequest,
  createEmvDataDecryptRequestSchema,
} from './createEmvDataDecryptRequest.js';

export interface CreateEmvDecryptRequest {
  iccData: string;
  cardSequenceNumber: string;
  data: CreateEmvDataDecryptRequest;
  poi?: CreateCardPaymentContactlessPOIRequest;
}

export const createEmvDecryptRequestSchema: Schema<CreateEmvDecryptRequest> = lazy(
  () =>
    object({
      iccData: ['icc_data', string()],
      cardSequenceNumber: ['card_sequence_number', string()],
      data: ['data', createEmvDataDecryptRequestSchema],
      poi: ['poi', optional(createCardPaymentContactlessPOIRequestSchema)],
    })
);
