/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

/** Creates a refund with split rules */
export interface CreateCancelChargeSplitRulesRequest {
  /** The split rule gateway id */
  id: string;
  /** The split rule amount */
  amount: number;
  /** The amount type (flat ou percentage) */
  type: string;
}

export const createCancelChargeSplitRulesRequestSchema: Schema<CreateCancelChargeSplitRulesRequest> = object(
  {
    id: ['id', string()],
    amount: ['Amount', number()],
    type: ['type', string()],
  }
);
