/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface CreatePhoneRequest {
  countryCode?: string;
  number?: string;
  areaCode?: string;
  type?: string | null;
}

export const createPhoneRequestSchema: Schema<CreatePhoneRequest> = object({
  countryCode: ['country_code', optional(string())],
  number: ['number', optional(string())],
  areaCode: ['area_code', optional(string())],
  type: ['Type', optional(nullable(string()))],
});
