/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema';
import {
  CreatePaymentRequest,
  createPaymentRequestSchema,
} from './createPaymentRequest';

/** Request for creating a Setup for a subscription. The setup is an order that will be created at the subscription creation. */
export interface CreateSetupRequest {
  /** Setup amount */
  amount: number;
  /** Description */
  description: string;
  /** Payment data */
  payment: CreatePaymentRequest;
}

export const createSetupRequestSchema: Schema<CreateSetupRequest> = object({
  amount: ['amount', number()],
  description: ['description', string()],
  payment: ['payment', lazy(() => createPaymentRequestSchema)],
});
