/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import {
  CreateSplitOptionsRequest,
  createSplitOptionsRequestSchema,
} from './createSplitOptionsRequest';

/** Split */
export interface CreateSplitRequest {
  /** Split type */
  type: string;
  /** Amount */
  amount: number;
  /** Recipient id */
  recipientId: string;
  /** The split options request */
  options?: CreateSplitOptionsRequest;
  /** Rule code used in cancellation. */
  splitRuleId?: string;
}

export const createSplitRequestSchema: Schema<CreateSplitRequest> = object({
  type: ['type', string()],
  amount: ['amount', number()],
  recipientId: ['recipient_id', string()],
  options: ['options', optional(lazy(() => createSplitOptionsRequestSchema))],
  splitRuleId: ['split_rule_id', optional(string())],
});
