/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import {
  CreatePricingSchemeRequest,
  createPricingSchemeRequestSchema,
} from './createPricingSchemeRequest';

/** Request for creating a plan item */
export interface CreatePlanItemRequest {
  /** Item name */
  name: string;
  /** Item's pricing scheme */
  pricingScheme: CreatePricingSchemeRequest;
  /** Item's id */
  id: string;
  /** Item's description */
  description: string;
  /** Number of cycles where the item will be charged */
  cycles?: number;
  /** Quantity */
  quantity?: number;
}

export const createPlanItemRequestSchema: Schema<CreatePlanItemRequest> = object(
  {
    name: ['name', string()],
    pricingScheme: [
      'pricing_scheme',
      lazy(() => createPricingSchemeRequestSchema),
    ],
    id: ['id', string()],
    description: ['description', string()],
    cycles: ['cycles', optional(number())],
    quantity: ['quantity', optional(number())],
  }
);
