/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CreatePeriodRequest {
  endAt?: string;
}

export const createPeriodRequestSchema: Schema<CreatePeriodRequest> = object({
  endAt: ['end_at', optional(string())],
});
