/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface CreateTransfer {
  amount: number;
  sourceId: string;
  targetId: string;
  metadata?: string[];
}

export const createTransferSchema: Schema<CreateTransfer> = object({
  amount: ['amount', number()],
  sourceId: ['source_id', string()],
  targetId: ['target_id', string()],
  metadata: ['metadata', optional(array(string()))],
});
