/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { discriminatedObject, Schema } from '../schema';
import {
  getBankTransferTransactionResponseSchema,
} from './getBankTransferTransactionResponse';
import {
  getBoletoTransactionResponseSchema,
} from './getBoletoTransactionResponse';
import { getCashTransactionResponseSchema } from './getCashTransactionResponse';
import {
  getCreditCardTransactionResponseSchema,
} from './getCreditCardTransactionResponse';
import {
  getDebitCardTransactionResponseSchema,
} from './getDebitCardTransactionResponse';
import { getPixTransactionResponseSchema } from './getPixTransactionResponse';
import {
  getPrivateLabelTransactionResponseSchema,
} from './getPrivateLabelTransactionResponse';
import {
  getSafetyPayTransactionResponseSchema,
} from './getSafetyPayTransactionResponse';
import { getTransactionResponseSchema } from './getTransactionResponse';
import {
  getVoucherTransactionResponseSchema,
} from './getVoucherTransactionResponse';

export const discriminatedGetTransactionResponseSchema: Schema<any> = discriminatedObject(
  'transactionType',
  'transaction_type',
  {
    'transaction': getTransactionResponseSchema,
    'voucher': getVoucherTransactionResponseSchema,
    'bank_transfer': getBankTransferTransactionResponseSchema,
    'safetypay': getSafetyPayTransactionResponseSchema,
    'debit_card': getDebitCardTransactionResponseSchema,
    'boleto': getBoletoTransactionResponseSchema,
    'cash': getCashTransactionResponseSchema,
    'private_label': getPrivateLabelTransactionResponseSchema,
    'pix': getPixTransactionResponseSchema,
    'credit_card': getCreditCardTransactionResponseSchema,
 },
  'transaction'
);

