/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { discriminatedObject, Schema } from '../schema.js';
import {
  GetBankTransferTransactionResponse,
  getBankTransferTransactionResponseSchema,
} from './getBankTransferTransactionResponse.js';
import {
  GetBoletoTransactionResponse,
  getBoletoTransactionResponseSchema,
} from './getBoletoTransactionResponse.js';
import {
  GetCashTransactionResponse,
  getCashTransactionResponseSchema,
} from './getCashTransactionResponse.js';
import {
  GetCreditCardTransactionResponse,
  getCreditCardTransactionResponseSchema,
} from './getCreditCardTransactionResponse.js';
import {
  GetDebitCardTransactionResponse,
  getDebitCardTransactionResponseSchema,
} from './getDebitCardTransactionResponse.js';
import {
  GetMovementObjectBaseResponse,
  getMovementObjectBaseResponseSchema,
} from './getMovementObjectBaseResponse.js';
import {
  GetMovementObjectFeeCollectionResponse,
  getMovementObjectFeeCollectionResponseSchema,
} from './getMovementObjectFeeCollectionResponse.js';
import {
  GetMovementObjectPayableResponse,
  getMovementObjectPayableResponseSchema,
} from './getMovementObjectPayableResponse.js';
import {
  GetMovementObjectRefundResponse,
  getMovementObjectRefundResponseSchema,
} from './getMovementObjectRefundResponse.js';
import {
  GetMovementObjectSettlementResponse,
  getMovementObjectSettlementResponseSchema,
} from './getMovementObjectSettlementResponse.js';
import {
  GetMovementObjectTransferResponse,
  getMovementObjectTransferResponseSchema,
} from './getMovementObjectTransferResponse.js';
import {
  GetPixTransactionResponse,
  getPixTransactionResponseSchema,
} from './getPixTransactionResponse.js';
import {
  GetPrivateLabelTransactionResponse,
  getPrivateLabelTransactionResponseSchema,
} from './getPrivateLabelTransactionResponse.js';
import {
  GetSafetyPayTransactionResponse,
  getSafetyPayTransactionResponseSchema,
} from './getSafetyPayTransactionResponse.js';
import {
  GetTransactionResponse,
  getTransactionResponseSchema,
} from './getTransactionResponse.js';
import {
  GetVoucherTransactionResponse,
  getVoucherTransactionResponseSchema,
} from './getVoucherTransactionResponse.js';

export const discriminatedGetTransactionResponseSchema: Schema<
  | GetTransactionResponse
  | GetSafetyPayTransactionResponse
  | GetVoucherTransactionResponse
  | GetBankTransferTransactionResponse
  | GetBoletoTransactionResponse
  | GetDebitCardTransactionResponse
  | GetCashTransactionResponse
  | GetPrivateLabelTransactionResponse
  | GetCreditCardTransactionResponse
  | GetPixTransactionResponse
> = discriminatedObject(
  'transactionType',
  'transaction_type',
  {
    'transaction': getTransactionResponseSchema,
    'safetypay': getSafetyPayTransactionResponseSchema,
    'voucher': getVoucherTransactionResponseSchema,
    'bank_transfer': getBankTransferTransactionResponseSchema,
    'boleto': getBoletoTransactionResponseSchema,
    'debit_card': getDebitCardTransactionResponseSchema,
    'cash': getCashTransactionResponseSchema,
    'private_label': getPrivateLabelTransactionResponseSchema,
    'credit_card': getCreditCardTransactionResponseSchema,
    'pix': getPixTransactionResponseSchema,
  },
  'transaction'
);
export const discriminatedGetMovementObjectBaseResponseSchema: Schema<
  | GetMovementObjectBaseResponse
  | GetMovementObjectFeeCollectionResponse
  | GetMovementObjectPayableResponse
  | GetMovementObjectRefundResponse
  | GetMovementObjectTransferResponse
  | GetMovementObjectSettlementResponse
> = discriminatedObject(
  'object',
  'object',
  {
    'MovementObject': getMovementObjectBaseResponseSchema,
    'feeCollection': getMovementObjectFeeCollectionResponseSchema,
    'payable': getMovementObjectPayableResponseSchema,
    'refund': getMovementObjectRefundResponseSchema,
    'transfer': getMovementObjectTransferResponseSchema,
    'settlement': getMovementObjectSettlementResponseSchema,
  },
  'MovementObject'
);
