/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface GetAntifraudResponse {
  status: string | null;
  returnCode: string | null;
  returnMessage: string | null;
  providerName: string | null;
  score: string | null;
}

export const getAntifraudResponseSchema: Schema<GetAntifraudResponse> = object({
  status: ['status', nullable(string())],
  returnCode: ['return_code', nullable(string())],
  returnMessage: ['return_message', nullable(string())],
  providerName: ['provider_name', nullable(string())],
  score: ['score', nullable(string())],
});
