/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema';
import {
  GetCustomerResponse,
  getCustomerResponseSchema,
} from './getCustomerResponse';

/** Response object for getting a access token */
export interface GetAccessTokenResponse {
  id?: string | null;
  code?: string | null;
  status?: string | null;
  createdAt?: string | null;
  customer?: GetCustomerResponse | null;
}

export const getAccessTokenResponseSchema: Schema<GetAccessTokenResponse> = object(
  {
    id: ['id', optional(nullable(string()))],
    code: ['code', optional(nullable(string()))],
    status: ['status', optional(nullable(string()))],
    createdAt: ['created_at', optional(nullable(string()))],
    customer: [
      'customer',
      optional(nullable(lazy(() => getCustomerResponseSchema))),
    ],
  }
);
