/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema } from '../schema';
import {
  GetAnticipationLimitResponse,
  getAnticipationLimitResponseSchema,
} from './getAnticipationLimitResponse';

/** Anticipation limits */
export interface GetAnticipationLimitsResponse {
  /** Max limit */
  max?: GetAnticipationLimitResponse | null;
  /** Min limit */
  min?: GetAnticipationLimitResponse | null;
}

export const getAnticipationLimitsResponseSchema: Schema<GetAnticipationLimitsResponse> = object(
  {
    max: [
      'max',
      optional(nullable(lazy(() => getAnticipationLimitResponseSchema))),
    ],
    min: [
      'min',
      optional(nullable(lazy(() => getAnticipationLimitResponseSchema))),
    ],
  }
);
