/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema } from '../schema';

/** Anticipation limit */
export interface GetAnticipationLimitResponse {
  /** Amount */
  amount?: number | null;
  /** Anticipation fee */
  anticipationFee?: number | null;
}

export const getAnticipationLimitResponseSchema: Schema<GetAnticipationLimitResponse> = object(
  {
    amount: ['amount', optional(nullable(number()))],
    anticipationFee: ['anticipation_fee', optional(nullable(number()))],
  }
);
