/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface GetAntifraudResponse {
  status?: string | null;
  returnCode?: string | null;
  returnMessage?: string | null;
  providerName?: string | null;
  score?: string | null;
}

export const getAntifraudResponseSchema: Schema<GetAntifraudResponse> = object({
  status: ['status', optional(nullable(string()))],
  returnCode: ['return_code', optional(nullable(string()))],
  returnMessage: ['return_message', optional(nullable(string()))],
  providerName: ['provider_name', optional(nullable(string()))],
  score: ['score', optional(nullable(string()))],
});
