/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema';

export interface GetAutomaticAnticipationResponse {
  enabled: boolean | null;
  type: string | null;
  volumePercentage: number | null;
  delay: number | null;
  days: number[] | null;
}

export const getAutomaticAnticipationResponseSchema: Schema<GetAutomaticAnticipationResponse> = object(
  {
    enabled: ['enabled', nullable(boolean())],
    type: ['type', nullable(string())],
    volumePercentage: ['volume_percentage', nullable(number())],
    delay: ['delay', nullable(number())],
    days: ['days', nullable(array(number()))],
  }
);
