/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  GetRecipientResponse,
  getRecipientResponseSchema,
} from './getRecipientResponse';

export interface GetBankAccountResponse {
  /** Id */
  id: string | null;
  /** Holder name */
  holderName: string | null;
  /** Holder type */
  holderType: string | null;
  /** Bank */
  bank: string | null;
  /** Branch number */
  branchNumber: string | null;
  /** Branch check digit */
  branchCheckDigit: string | null;
  /** Account number */
  accountNumber: string | null;
  /** Account check digit */
  accountCheckDigit: string | null;
  /** Bank account type */
  type: string | null;
  /** Bank account status */
  status: string | null;
  /** Creation date */
  createdAt: string | null;
  /** Last update date */
  updatedAt: string | null;
  /** Deletion date */
  deletedAt: string | null;
  /** Recipient */
  recipient?: GetRecipientResponse | null;
  /** Metadata */
  metadata: Record<string, string> | null;
  /** Pix Key */
  pixKey: string | null;
}

export const getBankAccountResponseSchema: Schema<GetBankAccountResponse> = object(
  {
    id: ['id', nullable(string())],
    holderName: ['holder_name', nullable(string())],
    holderType: ['holder_type', nullable(string())],
    bank: ['bank', nullable(string())],
    branchNumber: ['branch_number', nullable(string())],
    branchCheckDigit: ['branch_check_digit', nullable(string())],
    accountNumber: ['account_number', nullable(string())],
    accountCheckDigit: ['account_check_digit', nullable(string())],
    type: ['type', nullable(string())],
    status: ['status', nullable(string())],
    createdAt: ['created_at', nullable(string())],
    updatedAt: ['updated_at', nullable(string())],
    deletedAt: ['deleted_at', nullable(string())],
    recipient: [
      'recipient',
      optional(nullable(lazy(() => getRecipientResponseSchema))),
    ],
    metadata: ['metadata', nullable(dict(string()))],
    pixKey: ['pix_key', nullable(string())],
  }
);
