/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

/** Response object for getting a billing address */
export interface GetBillingAddressResponse {
  street: string | null;
  number: string | null;
  zipCode: string | null;
  neighborhood: string | null;
  city: string | null;
  state: string | null;
  country: string | null;
  complement: string | null;
  /** Line 1 for address */
  line1: string | null;
  /** Line 2 for address */
  line2: string | null;
}

export const getBillingAddressResponseSchema: Schema<GetBillingAddressResponse> = object(
  {
    street: ['street', nullable(string())],
    number: ['number', nullable(string())],
    zipCode: ['zip_code', nullable(string())],
    neighborhood: ['neighborhood', nullable(string())],
    city: ['city', nullable(string())],
    state: ['state', nullable(string())],
    country: ['country', nullable(string())],
    complement: ['complement', nullable(string())],
    line1: ['line_1', nullable(string())],
    line2: ['line_2', nullable(string())],
  }
);
