/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { getAntifraudResponseSchema } from './getAntifraudResponse.js';
import { getFineResponseSchema } from './getFineResponse.js';
import { getGatewayResponseResponseSchema } from './getGatewayResponseResponse.js';
import { getInterestResponseSchema } from './getInterestResponse.js';
import { getSplitResponseSchema } from './getSplitResponse.js';
import { GetTransactionResponse } from './getTransactionResponse.js';

/** Response object for getting a bank transfer transaction */
export interface GetBankTransferTransactionResponse extends GetTransactionResponse {
  /** Payment url */
  url?: string;
  /** Transaction identifier for the bank */
  bankTid?: string;
  /** Bank */
  bank?: string;
  /** Payment date */
  paidAt?: string;
  /** Paid amount */
  paidAmount?: number;
}

export const getBankTransferTransactionResponseSchema: Schema<GetBankTransferTransactionResponse> = lazy(
  () =>
    object({
      url: ['url', optional(string())],
      bankTid: ['bank_tid', optional(string())],
      bank: ['bank', optional(string())],
      paidAt: ['paid_at', optional(string())],
      paidAmount: ['paid_amount', optional(number())],
      gatewayId: ['gateway_id', optional(nullable(string()))],
      amount: ['amount', optional(nullable(number()))],
      status: ['status', optional(nullable(string()))],
      success: ['success', optional(nullable(boolean()))],
      createdAt: ['created_at', optional(nullable(string()))],
      updatedAt: ['updated_at', optional(nullable(string()))],
      attemptCount: ['attempt_count', optional(nullable(number()))],
      maxAttempts: ['max_attempts', optional(nullable(number()))],
      splits: ['splits', optional(nullable(array(getSplitResponseSchema)))],
      nextAttempt: ['next_attempt', optional(nullable(string()))],
      id: ['id', optional(nullable(string()))],
      gatewayResponse: [
        'gateway_response',
        optional(nullable(getGatewayResponseResponseSchema)),
      ],
      antifraudResponse: [
        'antifraud_response',
        optional(nullable(getAntifraudResponseSchema)),
      ],
      metadata: ['metadata', optional(nullable(dict(string())))],
      split: ['split', optional(nullable(array(getSplitResponseSchema)))],
      interest: ['interest', optional(nullable(getInterestResponseSchema))],
      fine: ['fine', optional(nullable(getFineResponseSchema))],
      maxDaysToPayPastDue: [
        'max_days_to_pay_past_due',
        optional(nullable(number())),
      ],
      transactionType: ['transaction_type', optional(string())],
    })
);
