/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  PixAdditionalInformation,
  pixAdditionalInformationSchema,
} from './pixAdditionalInformation';

/** Checkout pix payment response */
export interface GetCheckoutPixPaymentResponse {
  /** Expires at */
  expiresAt?: string | null;
  /** Additional information */
  additionalInformation?: PixAdditionalInformation[] | null;
}

export const getCheckoutPixPaymentResponseSchema: Schema<GetCheckoutPixPaymentResponse> = object(
  {
    expiresAt: ['expires_at', optional(nullable(string()))],
    additionalInformation: [
      'additional_information',
      optional(nullable(array(lazy(() => pixAdditionalInformationSchema)))),
    ],
  }
);
