/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

/** Card token data */
export interface GetCardTokenResponse {
  lastFourDigits?: string | null;
  holderName?: string | null;
  holderDocument?: string | null;
  expMonth?: number | null;
  expYear?: number | null;
  brand?: string | null;
  type?: string | null;
  label?: string | null;
}

export const getCardTokenResponseSchema: Schema<GetCardTokenResponse> = object({
  lastFourDigits: ['last_four_digits', optional(nullable(string()))],
  holderName: ['holder_name', optional(nullable(string()))],
  holderDocument: ['holder_document', optional(nullable(string()))],
  expMonth: ['exp_month', optional(nullable(number()))],
  expYear: ['exp_year', optional(nullable(number()))],
  brand: ['brand', optional(nullable(string()))],
  type: ['type', optional(nullable(string()))],
  label: ['label', optional(nullable(string()))],
});
