/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema';
import {
  GetPaymentAuthenticationResponse,
  getPaymentAuthenticationResponseSchema,
} from './getPaymentAuthenticationResponse';

export interface GetCheckoutDebitCardPaymentResponse {
  /** Descrição na fatura */
  statementDescriptor?: string | null;
  /** Payment Authentication response object data */
  authentication?: GetPaymentAuthenticationResponse | null;
}

export const getCheckoutDebitCardPaymentResponseSchema: Schema<GetCheckoutDebitCardPaymentResponse> = object(
  {
    statementDescriptor: ['statement_descriptor', optional(nullable(string()))],
    authentication: [
      'authentication',
      optional(nullable(lazy(() => getPaymentAuthenticationResponseSchema))),
    ],
  }
);
