/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema';

export interface GetCheckoutCardInstallmentOptionsResponse {
  /** Número de parcelas */
  number: string | null;
  /** Valor total da compra */
  total: number | null;
}

export const getCheckoutCardInstallmentOptionsResponseSchema: Schema<GetCheckoutCardInstallmentOptionsResponse> = object(
  {
    number: ['number', nullable(string())],
    total: ['total', nullable(number())],
  }
);
