/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  GetBillingAddressResponse,
  getBillingAddressResponseSchema,
} from './getBillingAddressResponse';
import {
  GetCustomerResponse,
  getCustomerResponseSchema,
} from './getCustomerResponse';

/** Response object for getting a credit card */
export interface GetCardResponse {
  id: string | null;
  lastFourDigits: string | null;
  brand: string | null;
  holderName: string | null;
  expMonth: number | null;
  expYear: number | null;
  status: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  billingAddress: GetBillingAddressResponse | null;
  customer?: GetCustomerResponse | null;
  metadata: Record<string, string> | null;
  /** Card type */
  type: string | null;
  /** Document number for the card's holder */
  holderDocument: string | null;
  deletedAt?: string | null;
  /** First six digits */
  firstSixDigits: string | null;
  label: string | null;
}

export const getCardResponseSchema: Schema<GetCardResponse> = object({
  id: ['id', nullable(string())],
  lastFourDigits: ['last_four_digits', nullable(string())],
  brand: ['brand', nullable(string())],
  holderName: ['holder_name', nullable(string())],
  expMonth: ['exp_month', nullable(number())],
  expYear: ['exp_year', nullable(number())],
  status: ['status', nullable(string())],
  createdAt: ['created_at', nullable(string())],
  updatedAt: ['updated_at', nullable(string())],
  billingAddress: [
    'billing_address',
    nullable(lazy(() => getBillingAddressResponseSchema)),
  ],
  customer: [
    'customer',
    optional(nullable(lazy(() => getCustomerResponseSchema))),
  ],
  metadata: ['metadata', nullable(dict(string()))],
  type: ['type', nullable(string())],
  holderDocument: ['holder_document', nullable(string())],
  deletedAt: ['deleted_at', optional(nullable(string()))],
  firstSixDigits: ['first_six_digits', nullable(string())],
  label: ['label', nullable(string())],
});
