/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, nullable, number, object, Schema } from '../schema';

export interface GetCheckoutCardInstallmentOptionsResponse {
  /** Número de parcelas */
  number: bigint | null;
  /** Valor total da compra */
  total: number | null;
}

export const getCheckoutCardInstallmentOptionsResponseSchema: Schema<GetCheckoutCardInstallmentOptionsResponse> = object(
  {
    number: ['number', nullable(bigint())],
    total: ['total', nullable(number())],
  }
);
