/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { getAntifraudResponseSchema } from './getAntifraudResponse.js';
import { GetCardResponse, getCardResponseSchema } from './getCardResponse.js';
import { getFineResponseSchema } from './getFineResponse.js';
import { getGatewayResponseResponseSchema } from './getGatewayResponseResponse.js';
import { getInterestResponseSchema } from './getInterestResponse.js';
import {
  GetRetryTransactionInformationResponse,
  getRetryTransactionInformationResponseSchema,
} from './getRetryTransactionInformationResponse.js';
import { getSplitResponseSchema } from './getSplitResponse.js';
import { GetTransactionResponse } from './getTransactionResponse.js';

/** Response object for getting a debit card transaction */
export interface GetDebitCardTransactionResponse extends GetTransactionResponse {
  /** Text that will appear on the debit card's statement */
  statementDescriptor?: string | null;
  /** Acquirer name */
  acquirerName?: string | null;
  /** Aquirer affiliation code */
  acquirerAffiliationCode?: string | null;
  /** Acquirer TID */
  acquirerTid?: string | null;
  /** Acquirer NSU */
  acquirerNsu?: string | null;
  /** Acquirer authorization code */
  acquirerAuthCode?: string | null;
  /** Operation type */
  operationType?: string | null;
  /** Card data */
  card?: GetCardResponse | null;
  /** Acquirer message */
  acquirerMessage?: string | null;
  /** Acquirer Return Code */
  acquirerReturnCode?: string | null;
  /** Merchant Plugin */
  mpi?: string | null;
  /** Electronic Commerce Indicator (ECI) */
  eci?: string | null;
  /** Authentication type */
  authenticationType?: string | null;
  /** 3D-S Authentication Url */
  threedAuthenticationUrl?: string | null;
  /** Identify when a card is prepaid, credit or debit. */
  fundingSource?: string | null;
  /** Retry transaction information */
  retryInfo?: GetRetryTransactionInformationResponse | null;
  brandId?: string | null;
}

export const getDebitCardTransactionResponseSchema: Schema<GetDebitCardTransactionResponse> = lazy(
  () =>
    object({
      statementDescriptor: [
        'statement_descriptor',
        optional(nullable(string())),
      ],
      acquirerName: ['acquirer_name', optional(nullable(string()))],
      acquirerAffiliationCode: [
        'acquirer_affiliation_code',
        optional(nullable(string())),
      ],
      acquirerTid: ['acquirer_tid', optional(nullable(string()))],
      acquirerNsu: ['acquirer_nsu', optional(nullable(string()))],
      acquirerAuthCode: ['acquirer_auth_code', optional(nullable(string()))],
      operationType: ['operation_type', optional(nullable(string()))],
      card: ['card', optional(nullable(getCardResponseSchema))],
      acquirerMessage: ['acquirer_message', optional(nullable(string()))],
      acquirerReturnCode: [
        'acquirer_return_code',
        optional(nullable(string())),
      ],
      mpi: ['mpi', optional(nullable(string()))],
      eci: ['eci', optional(nullable(string()))],
      authenticationType: ['authentication_type', optional(nullable(string()))],
      threedAuthenticationUrl: [
        'threed_authentication_url',
        optional(nullable(string())),
      ],
      fundingSource: ['funding_source', optional(nullable(string()))],
      retryInfo: [
        'retry_info',
        optional(nullable(getRetryTransactionInformationResponseSchema)),
      ],
      brandId: ['brand_id', optional(nullable(string()))],
      gatewayId: ['gateway_id', optional(nullable(string()))],
      amount: ['amount', optional(nullable(number()))],
      status: ['status', optional(nullable(string()))],
      success: ['success', optional(nullable(boolean()))],
      createdAt: ['created_at', optional(nullable(string()))],
      updatedAt: ['updated_at', optional(nullable(string()))],
      attemptCount: ['attempt_count', optional(nullable(number()))],
      maxAttempts: ['max_attempts', optional(nullable(number()))],
      splits: ['splits', optional(nullable(array(getSplitResponseSchema)))],
      nextAttempt: ['next_attempt', optional(nullable(string()))],
      id: ['id', optional(nullable(string()))],
      gatewayResponse: [
        'gateway_response',
        optional(nullable(getGatewayResponseResponseSchema)),
      ],
      antifraudResponse: [
        'antifraud_response',
        optional(nullable(getAntifraudResponseSchema)),
      ],
      metadata: ['metadata', optional(nullable(dict(string())))],
      split: ['split', optional(nullable(array(getSplitResponseSchema)))],
      interest: ['interest', optional(nullable(getInterestResponseSchema))],
      fine: ['fine', optional(nullable(getFineResponseSchema))],
      maxDaysToPayPastDue: [
        'max_days_to_pay_past_due',
        optional(nullable(number())),
      ],
      transactionType: ['transaction_type', optional(string())],
    })
);
