/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

/** Response object for geetting an order device */
export interface GetDeviceResponse {
  /** Device's platform name */
  platform?: string | null;
}

export const getDeviceResponseSchema: Schema<GetDeviceResponse> = object({
  platform: ['platform', optional(nullable(string()))],
});
