/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

/** Gateway Response */
export interface GetGatewayErrorResponse {
  /** The message error */
  message?: string | null;
}

export const getGatewayErrorResponseSchema: Schema<GetGatewayErrorResponse> = object(
  { message: ['message', optional(nullable(string()))] }
);
