/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  GetBillingAddressResponse,
  getBillingAddressResponseSchema,
} from './getBillingAddressResponse.js';
import {
  GetChargeResponse,
  getChargeResponseSchema,
} from './getChargeResponse.js';
import {
  GetCustomerResponse,
  getCustomerResponseSchema,
} from './getCustomerResponse.js';
import {
  GetInvoiceItemResponse,
  getInvoiceItemResponseSchema,
} from './getInvoiceItemResponse.js';
import {
  GetPeriodResponse,
  getPeriodResponseSchema,
} from './getPeriodResponse.js';
import {
  GetShippingResponse,
  getShippingResponseSchema,
} from './getShippingResponse.js';
import {
  GetSubscriptionResponse,
  getSubscriptionResponseSchema,
} from './getSubscriptionResponse.js';

/** Response object for getting an invoice */
export interface GetInvoiceResponse {
  id?: string | null;
  code?: string | null;
  url?: string | null;
  amount?: number | null;
  status?: string | null;
  paymentMethod?: string | null;
  createdAt?: string | null;
  items?: GetInvoiceItemResponse[] | null;
  customer?: GetCustomerResponse | null;
  charge?: GetChargeResponse | null;
  installments?: number | null;
  billingAddress?: GetBillingAddressResponse | null;
  subscription?: GetSubscriptionResponse | null;
  cycle?: GetPeriodResponse | null;
  shipping?: GetShippingResponse | null;
  metadata?: Record<string, string> | null;
  dueAt?: string | null;
  canceledAt?: string | null;
  billingAt?: string | null;
  seenAt?: string | null;
  /** Total discounted value */
  totalDiscount?: number | null;
  /** Total discounted value */
  totalIncrement?: number | null;
  /** Subscription Id */
  subscriptionId?: string | null;
}

export const getInvoiceResponseSchema: Schema<GetInvoiceResponse> = lazy(() =>
  object({
    id: ['id', optional(nullable(string()))],
    code: ['code', optional(nullable(string()))],
    url: ['url', optional(nullable(string()))],
    amount: ['amount', optional(nullable(number()))],
    status: ['status', optional(nullable(string()))],
    paymentMethod: ['payment_method', optional(nullable(string()))],
    createdAt: ['created_at', optional(nullable(string()))],
    items: ['items', optional(nullable(array(getInvoiceItemResponseSchema)))],
    customer: ['customer', optional(nullable(getCustomerResponseSchema))],
    charge: ['charge', optional(nullable(getChargeResponseSchema))],
    installments: ['installments', optional(nullable(number()))],
    billingAddress: [
      'billing_address',
      optional(nullable(getBillingAddressResponseSchema)),
    ],
    subscription: [
      'subscription',
      optional(nullable(getSubscriptionResponseSchema)),
    ],
    cycle: ['cycle', optional(nullable(getPeriodResponseSchema))],
    shipping: ['shipping', optional(nullable(getShippingResponseSchema))],
    metadata: ['metadata', optional(nullable(dict(string())))],
    dueAt: ['due_at', optional(nullable(string()))],
    canceledAt: ['canceled_at', optional(nullable(string()))],
    billingAt: ['billing_at', optional(nullable(string()))],
    seenAt: ['seen_at', optional(nullable(string()))],
    totalDiscount: ['total_discount', optional(nullable(number()))],
    totalIncrement: ['total_increment', optional(nullable(number()))],
    subscriptionId: ['subscription_id', optional(nullable(string()))],
  })
);
