/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema';

/** Interest Response */
export interface GetInterestResponse {
  /** Days */
  days: number | null;
  /** Type */
  type: string | null;
  /** Amount */
  amount: number | null;
}

export const getInterestResponseSchema: Schema<GetInterestResponse> = object({
  days: ['days', nullable(number())],
  type: ['type', nullable(string())],
  amount: ['amount', nullable(number())],
});
