/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  GetPriceBracketResponse,
  getPriceBracketResponseSchema,
} from './getPriceBracketResponse';
import {
  GetPricingSchemeResponse,
  getPricingSchemeResponseSchema,
} from './getPricingSchemeResponse';

/** Response object for getting an invoice item */
export interface GetInvoiceItemResponse {
  amount?: number | null;
  description?: string | null;
  pricingScheme?: GetPricingSchemeResponse | null;
  priceBracket?: GetPriceBracketResponse | null;
  quantity?: number | null;
  name?: string | null;
  /** Subscription Item Id */
  subscriptionItemId?: string | null;
}

export const getInvoiceItemResponseSchema: Schema<GetInvoiceItemResponse> = object(
  {
    amount: ['amount', optional(nullable(number()))],
    description: ['description', optional(nullable(string()))],
    pricingScheme: [
      'pricing_scheme',
      optional(nullable(lazy(() => getPricingSchemeResponseSchema))),
    ],
    priceBracket: [
      'price_bracket',
      optional(nullable(lazy(() => getPriceBracketResponseSchema))),
    ],
    quantity: ['quantity', optional(nullable(number()))],
    name: ['name', optional(nullable(string()))],
    subscriptionItemId: ['subscription_item_id', optional(nullable(string()))],
  }
);
