/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

/** Response object for geetting an order location request */
export interface GetLocationResponse {
  /** Latitude */
  latitude?: string | null;
  /** Longitude */
  longitude?: string | null;
}

export const getLocationResponseSchema: Schema<GetLocationResponse> = object({
  latitude: ['latitude', optional(nullable(string()))],
  longitude: ['longitude', optional(nullable(string()))],
});
