/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';
import { GetMovementObjectBaseResponse } from './getMovementObjectBaseResponse';

export interface GetMovementObjectPayableResponse extends GetMovementObjectBaseResponse {
  fee?: string | null;
  anticipationFee: string;
  fraudCoverageFee: string;
  installment: string;
  splitId: string;
  bulkAnticipationId: string;
  anticipationId: string;
  recipientId: string;
  originatorModel: string;
  originatorModelId: string;
  paymentDate: string;
  originalPaymentDate: string;
  paymentMethod: string;
  accrualAt: string;
  liquidationArrangementId: string;
}

export const getMovementObjectPayableResponseSchema: Schema<GetMovementObjectPayableResponse> = object(
  {
    fee: ['fee', optional(nullable(string()))],
    anticipationFee: ['anticipation_fee', string()],
    fraudCoverageFee: ['fraud_coverage_fee', string()],
    installment: ['installment', string()],
    splitId: ['split_id', string()],
    bulkAnticipationId: ['bulk_anticipation_id', string()],
    anticipationId: ['anticipation_id', string()],
    recipientId: ['recipient_id', string()],
    originatorModel: ['originator_model', string()],
    originatorModelId: ['originator_model_id', string()],
    paymentDate: ['payment_date', string()],
    originalPaymentDate: ['original_payment_date', string()],
    paymentMethod: ['payment_method', string()],
    accrualAt: ['accrual_at', string()],
    liquidationArrangementId: ['liquidation_arrangement_id', string()],
    id: ['id', optional(nullable(string()))],
    status: ['status', optional(nullable(string()))],
    amount: ['amount', optional(nullable(string()))],
    createdAt: ['created_at', optional(nullable(string()))],
    type: ['type', optional(nullable(string()))],
    chargeId: ['charge_id', optional(nullable(string()))],
    gatewayId: ['gateway_id', optional(nullable(string()))],
    object: ['object', optional(string())],
  }
);
