/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { GetPlanResponse, getPlanResponseSchema } from './getPlanResponse';
import {
  GetPricingSchemeResponse,
  getPricingSchemeResponseSchema,
} from './getPricingSchemeResponse';

/** Response object for getting a plan item */
export interface GetPlanItemResponse {
  id?: string | null;
  name?: string | null;
  status?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  pricingScheme?: GetPricingSchemeResponse | null;
  description?: string | null;
  plan?: GetPlanResponse | null;
  quantity?: number | null;
  cycles?: number | null;
  deletedAt?: string | null;
}

export const getPlanItemResponseSchema: Schema<GetPlanItemResponse> = object({
  id: ['id', optional(nullable(string()))],
  name: ['name', optional(nullable(string()))],
  status: ['status', optional(nullable(string()))],
  createdAt: ['created_at', optional(nullable(string()))],
  updatedAt: ['updated_at', optional(nullable(string()))],
  pricingScheme: [
    'pricing_scheme',
    optional(nullable(lazy(() => getPricingSchemeResponseSchema))),
  ],
  description: ['description', optional(nullable(string()))],
  plan: ['plan', optional(nullable(lazy(() => getPlanResponseSchema)))],
  quantity: ['quantity', optional(nullable(number()))],
  cycles: ['cycles', optional(nullable(number()))],
  deletedAt: ['deleted_at', optional(nullable(string()))],
});
