/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

/** Response object for getting an PhoneNumberResponse */
export interface GetPhoneNumberResponse {
  ddd?: string | null;
  number?: string | null;
  type?: string | null;
}

export const getPhoneNumberResponseSchema: Schema<GetPhoneNumberResponse> = object(
  {
    ddd: ['ddd', optional(nullable(string()))],
    number: ['number', optional(nullable(string()))],
    type: ['type', optional(nullable(string()))],
  }
);
