/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  GetManagingPartnerResponse,
  getManagingPartnerResponseSchema,
} from './getManagingPartnerResponse';
import {
  GetPhoneNumberResponse,
  getPhoneNumberResponseSchema,
} from './getPhoneNumberResponse';
import {
  GetRegisterInformationAddressResponse,
  getRegisterInformationAddressResponseSchema,
} from './getRegisterInformationAddressResponse';

/** Response object for getting an RegisterInformationResponse */
export interface GetRegisterInformationResponse {
  email?: string | null;
  document?: string | null;
  type?: string | null;
  siteUrl?: string | null;
  phoneNumbers?: GetPhoneNumberResponse[] | null;
  name?: string | null;
  motherName?: string | null;
  birthdate?: string | null;
  monthlyIncome?: string | null;
  professionalOccupation?: string | null;
  address?: GetRegisterInformationAddressResponse | null;
  companyName?: string | null;
  tradingName?: string | null;
  annualRevenue?: string | null;
  corporationType?: string | null;
  foundingDate?: string | null;
  cnae?: string | null;
  mainAddress?: GetRegisterInformationAddressResponse | null;
  managingPartners?: GetManagingPartnerResponse[] | null;
}

export const getRegisterInformationResponseSchema: Schema<GetRegisterInformationResponse> = object(
  {
    email: ['email', optional(nullable(string()))],
    document: ['document', optional(nullable(string()))],
    type: ['type', optional(nullable(string()))],
    siteUrl: ['site_url', optional(nullable(string()))],
    phoneNumbers: [
      'phone_numbers',
      optional(nullable(array(lazy(() => getPhoneNumberResponseSchema)))),
    ],
    name: ['name', optional(nullable(string()))],
    motherName: ['mother_name', optional(nullable(string()))],
    birthdate: ['birthdate', optional(nullable(string()))],
    monthlyIncome: ['monthly_income', optional(nullable(string()))],
    professionalOccupation: [
      'professional_occupation',
      optional(nullable(string())),
    ],
    address: [
      'address',
      optional(
        nullable(lazy(() => getRegisterInformationAddressResponseSchema))
      ),
    ],
    companyName: ['company_name', optional(nullable(string()))],
    tradingName: ['trading_name', optional(nullable(string()))],
    annualRevenue: ['annual_revenue', optional(nullable(string()))],
    corporationType: ['corporation_type', optional(nullable(string()))],
    foundingDate: ['founding_date', optional(nullable(string()))],
    cnae: ['cnae', optional(nullable(string()))],
    mainAddress: [
      'main_address',
      optional(
        nullable(lazy(() => getRegisterInformationAddressResponseSchema))
      ),
    ],
    managingPartners: [
      'managing_partners',
      optional(nullable(array(lazy(() => getManagingPartnerResponseSchema)))),
    ],
  }
);
