/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  GetAutomaticAnticipationResponse,
  getAutomaticAnticipationResponseSchema,
} from './getAutomaticAnticipationResponse';
import {
  GetBankAccountResponse,
  getBankAccountResponseSchema,
} from './getBankAccountResponse';
import {
  GetGatewayRecipientResponse,
  getGatewayRecipientResponseSchema,
} from './getGatewayRecipientResponse';
import {
  GetTransferSettingsResponse,
  getTransferSettingsResponseSchema,
} from './getTransferSettingsResponse';

/** Recipient response */
export interface GetRecipientResponse {
  /** Id */
  id: string | null;
  /** Name */
  name: string | null;
  /** Email */
  email: string | null;
  /** Document */
  document: string | null;
  /** Description */
  description: string | null;
  /** Type */
  type: string | null;
  /** Status */
  status: string | null;
  /** Creation date */
  createdAt: string | null;
  /** Last update date */
  updatedAt: string | null;
  /** Deletion date */
  deletedAt: string | null;
  /** Default bank account */
  defaultBankAccount: GetBankAccountResponse | null;
  /** Info about the recipient on the gateway */
  gatewayRecipients: GetGatewayRecipientResponse[] | null;
  /** Metadata */
  metadata: Record<string, string> | null;
  automaticAnticipationSettings?: GetAutomaticAnticipationResponse | null;
  transferSettings?: GetTransferSettingsResponse | null;
  /** Recipient code */
  code: string | null;
  /** Payment mode */
  paymentMode: string | null;
}

export const getRecipientResponseSchema: Schema<GetRecipientResponse> = object({
  id: ['id', nullable(string())],
  name: ['name', nullable(string())],
  email: ['email', nullable(string())],
  document: ['document', nullable(string())],
  description: ['description', nullable(string())],
  type: ['type', nullable(string())],
  status: ['status', nullable(string())],
  createdAt: ['created_at', nullable(string())],
  updatedAt: ['updated_at', nullable(string())],
  deletedAt: ['deleted_at', nullable(string())],
  defaultBankAccount: [
    'default_bank_account',
    nullable(lazy(() => getBankAccountResponseSchema)),
  ],
  gatewayRecipients: [
    'gateway_recipients',
    nullable(array(lazy(() => getGatewayRecipientResponseSchema))),
  ],
  metadata: ['metadata', nullable(dict(string()))],
  automaticAnticipationSettings: [
    'automatic_anticipation_settings',
    optional(nullable(lazy(() => getAutomaticAnticipationResponseSchema))),
  ],
  transferSettings: [
    'transfer_settings',
    optional(nullable(lazy(() => getTransferSettingsResponseSchema))),
  ],
  code: ['code', nullable(string())],
  paymentMode: ['payment_mode', nullable(string())],
});
