/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  GetDiscountResponse,
  getDiscountResponseSchema,
} from './getDiscountResponse';
import {
  GetIncrementResponse,
  getIncrementResponseSchema,
} from './getIncrementResponse';
import {
  GetPricingSchemeResponse,
  getPricingSchemeResponseSchema,
} from './getPricingSchemeResponse';
import {
  GetSubscriptionResponse,
  getSubscriptionResponseSchema,
} from './getSubscriptionResponse';

export interface GetSubscriptionItemResponse {
  id?: string | null;
  description?: string | null;
  status?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  pricingScheme?: GetPricingSchemeResponse | null;
  discounts?: GetDiscountResponse[] | null;
  increments?: GetIncrementResponse[] | null;
  subscription?: GetSubscriptionResponse | null;
  /** Item name */
  name?: string | null;
  quantity?: number | null;
  cycles?: number | null;
  deletedAt?: string | null;
}

export const getSubscriptionItemResponseSchema: Schema<GetSubscriptionItemResponse> = object(
  {
    id: ['id', optional(nullable(string()))],
    description: ['description', optional(nullable(string()))],
    status: ['status', optional(nullable(string()))],
    createdAt: ['created_at', optional(nullable(string()))],
    updatedAt: ['updated_at', optional(nullable(string()))],
    pricingScheme: [
      'pricing_scheme',
      optional(nullable(lazy(() => getPricingSchemeResponseSchema))),
    ],
    discounts: [
      'discounts',
      optional(nullable(array(lazy(() => getDiscountResponseSchema)))),
    ],
    increments: [
      'increments',
      optional(nullable(array(lazy(() => getIncrementResponseSchema)))),
    ],
    subscription: [
      'subscription',
      optional(nullable(lazy(() => getSubscriptionResponseSchema))),
    ],
    name: ['name', optional(nullable(string()))],
    quantity: ['quantity', optional(nullable(number()))],
    cycles: ['cycles', optional(nullable(number()))],
    deletedAt: ['deleted_at', optional(nullable(string()))],
  }
);
