/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, number, object, optional, Schema } from '../schema.js';
import { GetFineResponse, getFineResponseSchema } from './getFineResponse.js';
import {
  GetInterestResponse,
  getInterestResponseSchema,
} from './getInterestResponse.js';

/** Response object for getting a boleto */
export interface GetSubscriptionBoletoResponse {
  /** Interest */
  interest?: GetInterestResponse | null;
  /** Fine */
  fine?: GetFineResponse | null;
  maxDaysToPayPastDue?: number | null;
}

export const getSubscriptionBoletoResponseSchema: Schema<GetSubscriptionBoletoResponse> = lazy(
  () =>
    object({
      interest: ['interest', optional(nullable(getInterestResponseSchema))],
      fine: ['fine', optional(nullable(getFineResponseSchema))],
      maxDaysToPayPastDue: [
        'max_days_to_pay_past_due',
        optional(nullable(number())),
      ],
    })
);
