/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  object,
  optional,
  Schema,
} from '../schema.js';
import {
  GetSplitResponse,
  getSplitResponseSchema,
} from './getSplitResponse.js';

export interface GetSubscriptionSplitResponse {
  /** Defines if the split is enabled */
  enabled?: boolean | null;
  /** Split */
  rules?: GetSplitResponse[] | null;
}

export const getSubscriptionSplitResponseSchema: Schema<GetSubscriptionSplitResponse> = lazy(
  () =>
    object({
      enabled: ['enabled', optional(nullable(boolean()))],
      rules: ['rules', optional(nullable(array(getSplitResponseSchema)))],
    })
);
