/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, number, object, Schema, string } from '../schema';

export interface GetTransferSettingsResponse {
  transferEnabled: boolean | null;
  transferInterval: string | null;
  transferDay: number | null;
}

export const getTransferSettingsResponseSchema: Schema<GetTransferSettingsResponse> = object(
  {
    transferEnabled: ['transfer_enabled', nullable(boolean())],
    transferInterval: ['transfer_interval', nullable(string())],
    transferDay: ['transfer_day', nullable(number())],
  }
);
