/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface GetTransactionReportFileResponse {
  name: string | null;
  date: string | null;
}

export const getTransactionReportFileResponseSchema: Schema<GetTransactionReportFileResponse> = object(
  { name: ['name', nullable(string())], date: ['date', nullable(string())] }
);
