/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface GetTransferSourceResponse {
  sourceId?: string | null;
  type?: string | null;
}

export const getTransferSourceResponseSchema: Schema<GetTransferSourceResponse> = object(
  {
    sourceId: ['source_id', optional(nullable(string()))],
    type: ['type', optional(nullable(string()))],
  }
);
