/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

/** 3D-S payment authentication response */
export interface GetThreeDSecureResponse {
  /** MPI Vendor */
  mpi?: string | null;
  /** Electronic Commerce Indicator (ECI) (Opcional) */
  eci?: string | null;
  /** Online payment cryptogram, definido pelo 3-D Secure. */
  cavv?: string | null;
  /** Identificador da transação (XID) */
  transactionId?: string | null;
  /** Url de redirecionamento de sucessso */
  successUrl?: string | null;
}

export const getThreeDSecureResponseSchema: Schema<GetThreeDSecureResponse> = object(
  {
    mpi: ['mpi', optional(nullable(string()))],
    eci: ['eci', optional(nullable(string()))],
    cavv: ['cavv', optional(nullable(string()))],
    transactionId: ['transaction_Id', optional(nullable(string()))],
    successUrl: ['success_url', optional(nullable(string()))],
  }
);
