/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface GetUsageReportResponse {
  url: string | null;
  usageReportUrl: string | null;
  groupedReportUrl: string | null;
}

export const getUsageReportResponseSchema: Schema<GetUsageReportResponse> = object(
  {
    url: ['url', nullable(string())],
    usageReportUrl: ['usage_report_url', nullable(string())],
    groupedReportUrl: ['grouped_report_url', nullable(string())],
  }
);
