/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface GetWithdrawTargetResponse {
  targetId?: string | null;
  type?: string | null;
}

export const getWithdrawTargetResponseSchema: Schema<GetWithdrawTargetResponse> = object(
  {
    targetId: ['target_id', optional(nullable(string()))],
    type: ['type', optional(nullable(string()))],
  }
);
