/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { discriminatedGetTransactionResponseSchema } from '../models/discriminatedSchemas.js';
import { array, lazy, nullable, object, optional, Schema } from '../schema.js';
import { GetTransactionResponse } from './getTransactionResponse.js';
import { PagingResponse, pagingResponseSchema } from './pagingResponse.js';

/** Response object for listing transactions */
export interface ListTransactionsResponse {
  /** The transaction objects */
  data?: GetTransactionResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listTransactionsResponseSchema: Schema<ListTransactionsResponse> = lazy(
  () =>
    object({
      data: [
        'data',
        optional(nullable(array(discriminatedGetTransactionResponseSchema))),
      ],
      paging: ['paging', optional(nullable(pagingResponseSchema))],
    })
);
