/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema.js';
import {
  GetOrderResponse,
  getOrderResponseSchema,
} from './getOrderResponse.js';
import { PagingResponse, pagingResponseSchema } from './pagingResponse.js';

/** Response object for listing order objects */
export interface ListOrderResponse {
  /** The order object */
  data?: GetOrderResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listOrderResponseSchema: Schema<ListOrderResponse> = lazy(() =>
  object({
    data: ['data', optional(nullable(array(getOrderResponseSchema)))],
    paging: ['paging', optional(nullable(pagingResponseSchema))],
  })
);
