/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema';
import {
  GetAddressResponse,
  getAddressResponseSchema,
} from './getAddressResponse';
import { PagingResponse, pagingResponseSchema } from './pagingResponse';

/** Response object for listing addresses */
export interface ListAddressesResponse {
  /** The address objects */
  data?: GetAddressResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listAddressesResponseSchema: Schema<ListAddressesResponse> = object(
  {
    data: [
      'data',
      optional(nullable(array(lazy(() => getAddressResponseSchema)))),
    ],
    paging: ['paging', optional(nullable(lazy(() => pagingResponseSchema)))],
  }
);
