/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, Schema } from '../schema';
import { GetCardResponse, getCardResponseSchema } from './getCardResponse';
import { PagingResponse, pagingResponseSchema } from './pagingResponse';

/** Response object for listing cards */
export interface ListCardsResponse {
  /** The card objects */
  data: GetCardResponse[] | null;
  /** Paging object */
  paging: PagingResponse | null;
}

export const listCardsResponseSchema: Schema<ListCardsResponse> = object({
  data: ['data', nullable(array(lazy(() => getCardResponseSchema)))],
  paging: ['paging', nullable(lazy(() => pagingResponseSchema))],
});
