/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema';
import {
  GetChargeResponse,
  getChargeResponseSchema,
} from './getChargeResponse';
import { PagingResponse, pagingResponseSchema } from './pagingResponse';

/** Response object for listing charges */
export interface ListChargesResponse {
  /** The charge objects */
  data?: GetChargeResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listChargesResponseSchema: Schema<ListChargesResponse> = object({
  data: [
    'data',
    optional(nullable(array(lazy(() => getChargeResponseSchema)))),
  ],
  paging: ['paging', optional(nullable(lazy(() => pagingResponseSchema)))],
});
