/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema.js';
import {
  GetPeriodResponse,
  getPeriodResponseSchema,
} from './getPeriodResponse.js';
import { PagingResponse, pagingResponseSchema } from './pagingResponse.js';

/** Response object for listing subscription cycles */
export interface ListCyclesResponse {
  /** The subscription cycles objects */
  data?: GetPeriodResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listCyclesResponseSchema: Schema<ListCyclesResponse> = lazy(() =>
  object({
    data: ['data', optional(nullable(array(getPeriodResponseSchema)))],
    paging: ['paging', optional(nullable(pagingResponseSchema))],
  })
);
