/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema';
import {
  GetAnticipationResponse,
  getAnticipationResponseSchema,
} from './getAnticipationResponse';
import { PagingResponse, pagingResponseSchema } from './pagingResponse';

/** Anticipations */
export interface ListAnticipationResponse {
  /** Anticipations */
  data?: GetAnticipationResponse[] | null;
  /** Paging */
  paging?: PagingResponse | null;
}

export const listAnticipationResponseSchema: Schema<ListAnticipationResponse> = object(
  {
    data: [
      'data',
      optional(nullable(array(lazy(() => getAnticipationResponseSchema)))),
    ],
    paging: ['paging', optional(nullable(lazy(() => pagingResponseSchema)))],
  }
);
