/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema.js';
import {
  GetAddressResponse,
  getAddressResponseSchema,
} from './getAddressResponse.js';
import { PagingResponse, pagingResponseSchema } from './pagingResponse.js';

/** Response object for listing addresses */
export interface ListAddressesResponse {
  /** The address objects */
  data?: GetAddressResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listAddressesResponseSchema: Schema<ListAddressesResponse> = lazy(
  () =>
    object({
      data: ['data', optional(nullable(array(getAddressResponseSchema)))],
      paging: ['paging', optional(nullable(pagingResponseSchema))],
    })
);
