/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema.js';
import {
  GetChargeResponse,
  getChargeResponseSchema,
} from './getChargeResponse.js';
import { PagingResponse, pagingResponseSchema } from './pagingResponse.js';

/** Response object for listing charges */
export interface ListChargesResponse {
  /** The charge objects */
  data?: GetChargeResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listChargesResponseSchema: Schema<ListChargesResponse> = lazy(() =>
  object({
    data: ['data', optional(nullable(array(getChargeResponseSchema)))],
    paging: ['paging', optional(nullable(pagingResponseSchema))],
  })
);
