/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema.js';
import {
  GetSubscriptionItemResponse,
  getSubscriptionItemResponseSchema,
} from './getSubscriptionItemResponse.js';
import { PagingResponse, pagingResponseSchema } from './pagingResponse.js';

/** Response model for listing subscription items */
export interface ListSubscriptionItemsResponse {
  /** The subscription items */
  data?: GetSubscriptionItemResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listSubscriptionItemsResponseSchema: Schema<ListSubscriptionItemsResponse> = lazy(
  () =>
    object({
      data: [
        'data',
        optional(nullable(array(getSubscriptionItemResponseSchema))),
      ],
      paging: ['paging', optional(nullable(pagingResponseSchema))],
    })
);
