/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema';
import {
  GetIncrementResponse,
  getIncrementResponseSchema,
} from './getIncrementResponse';
import { PagingResponse, pagingResponseSchema } from './pagingResponse';

export interface ListIncrementsResponse {
  /** The Increments response */
  data?: GetIncrementResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listIncrementsResponseSchema: Schema<ListIncrementsResponse> = object(
  {
    data: [
      'data',
      optional(nullable(array(lazy(() => getIncrementResponseSchema)))),
    ],
    paging: ['paging', optional(nullable(lazy(() => pagingResponseSchema)))],
  }
);
