/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema';
import {
  GetInvoiceResponse,
  getInvoiceResponseSchema,
} from './getInvoiceResponse';
import { PagingResponse, pagingResponseSchema } from './pagingResponse';

/** Response object for listing invoices */
export interface ListInvoicesResponse {
  /** The Invoice objects */
  data?: GetInvoiceResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listInvoicesResponseSchema: Schema<ListInvoicesResponse> = object({
  data: [
    'data',
    optional(nullable(array(lazy(() => getInvoiceResponseSchema)))),
  ],
  paging: ['paging', optional(nullable(lazy(() => pagingResponseSchema)))],
});
