/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema';
import { GetPlanResponse, getPlanResponseSchema } from './getPlanResponse';
import { PagingResponse, pagingResponseSchema } from './pagingResponse';

/** Response object for listing plans */
export interface ListPlansResponse {
  /** The plan objects */
  data?: GetPlanResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listPlansResponseSchema: Schema<ListPlansResponse> = object({
  data: ['data', optional(nullable(array(lazy(() => getPlanResponseSchema))))],
  paging: ['paging', optional(nullable(lazy(() => pagingResponseSchema)))],
});
