/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema.js';
import {
  GetUsageResponse,
  getUsageResponseSchema,
} from './getUsageResponse.js';
import { PagingResponse, pagingResponseSchema } from './pagingResponse.js';

/** Response model for listing the usages from a subscription item */
export interface ListUsagesResponse {
  /** The usage objects */
  data?: GetUsageResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listUsagesResponseSchema: Schema<ListUsagesResponse> = lazy(() =>
  object({
    data: ['data', optional(nullable(array(getUsageResponseSchema)))],
    paging: ['paging', optional(nullable(pagingResponseSchema))],
  })
);
