/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema.js';
import {
  GetIncrementResponse,
  getIncrementResponseSchema,
} from './getIncrementResponse.js';
import { PagingResponse, pagingResponseSchema } from './pagingResponse.js';

export interface ListIncrementsResponse {
  /** The Increments response */
  data?: GetIncrementResponse[] | null;
  /** Paging object */
  paging?: PagingResponse | null;
}

export const listIncrementsResponseSchema: Schema<ListIncrementsResponse> = lazy(
  () =>
    object({
      data: ['data', optional(nullable(array(getIncrementResponseSchema)))],
      paging: ['paging', optional(nullable(pagingResponseSchema))],
    })
);
