/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema.js';
import {
  GetRecipientResponse,
  getRecipientResponseSchema,
} from './getRecipientResponse.js';
import { PagingResponse, pagingResponseSchema } from './pagingResponse.js';

/** Response for the listing recipient method */
export interface ListRecipientResponse {
  /** Recipients */
  data?: GetRecipientResponse[] | null;
  /** Paging */
  paging?: PagingResponse | null;
}

export const listRecipientResponseSchema: Schema<ListRecipientResponse> = lazy(
  () =>
    object({
      data: ['data', optional(nullable(array(getRecipientResponseSchema)))],
      paging: ['paging', optional(nullable(pagingResponseSchema))],
    })
);
