/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  CreateBankAccountRequest,
  createBankAccountRequestSchema,
} from './createBankAccountRequest.js';

/** Updates the default bank account for a recipient */
export interface UpdateRecipientBankAccountRequest {
  /** Bank account */
  bankAccount: CreateBankAccountRequest;
  /** Payment mode */
  paymentMode: string;
}

export const updateRecipientBankAccountRequestSchema: Schema<UpdateRecipientBankAccountRequest> = lazy(
  () =>
    object({
      bankAccount: ['bank_account', createBankAccountRequestSchema],
      paymentMode: ['payment_mode', string()],
    })
);
