/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Request to update the end date of the current subscription cycle */
export interface UpdateCurrentCycleEndDateRequest {
  /** Current cycle end date */
  endAt?: string;
}

export const updateCurrentCycleEndDateRequestSchema: Schema<UpdateCurrentCycleEndDateRequest> = object(
  { endAt: ['end_at', optional(string())] }
);
