/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, Schema, string } from '../schema.js';
import {
  CreateBankTransferPaymentRequest,
  createBankTransferPaymentRequestSchema,
} from './createBankTransferPaymentRequest.js';
import {
  CreateBoletoPaymentRequest,
  createBoletoPaymentRequestSchema,
} from './createBoletoPaymentRequest.js';
import {
  CreateCashPaymentRequest,
  createCashPaymentRequestSchema,
} from './createCashPaymentRequest.js';
import {
  CreateCreditCardPaymentRequest,
  createCreditCardPaymentRequestSchema,
} from './createCreditCardPaymentRequest.js';
import {
  CreateDebitCardPaymentRequest,
  createDebitCardPaymentRequestSchema,
} from './createDebitCardPaymentRequest.js';
import {
  CreatePrivateLabelPaymentRequest,
  createPrivateLabelPaymentRequestSchema,
} from './createPrivateLabelPaymentRequest.js';
import {
  CreateVoucherPaymentRequest,
  createVoucherPaymentRequestSchema,
} from './createVoucherPaymentRequest.js';

/** Request for updating the payment method of a charge */
export interface UpdateChargePaymentMethodRequest {
  /** Indicates if the payment method from the subscription must also be updated */
  updateSubscription: boolean;
  /** The new payment method */
  paymentMethod: string;
  /** Credit card data */
  creditCard: CreateCreditCardPaymentRequest;
  /** Debit card data */
  debitCard: CreateDebitCardPaymentRequest;
  /** Boleto data */
  boleto: CreateBoletoPaymentRequest;
  /** Voucher data */
  voucher: CreateVoucherPaymentRequest;
  /** Cash data */
  cash: CreateCashPaymentRequest;
  /** Bank Transfer data */
  bankTransfer: CreateBankTransferPaymentRequest;
  privateLabel: CreatePrivateLabelPaymentRequest;
}

export const updateChargePaymentMethodRequestSchema: Schema<UpdateChargePaymentMethodRequest> = lazy(
  () =>
    object({
      updateSubscription: ['update_subscription', boolean()],
      paymentMethod: ['payment_method', string()],
      creditCard: ['credit_card', createCreditCardPaymentRequestSchema],
      debitCard: ['debit_card', createDebitCardPaymentRequestSchema],
      boleto: ['boleto', createBoletoPaymentRequestSchema],
      voucher: ['voucher', createVoucherPaymentRequestSchema],
      cash: ['cash', createCashPaymentRequestSchema],
      bankTransfer: ['bank_transfer', createBankTransferPaymentRequestSchema],
      privateLabel: ['private_label', createPrivateLabelPaymentRequestSchema],
    })
);
