/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, Schema } from '../schema';
import {
  CreateSplitRequest,
  createSplitRequestSchema,
} from './createSplitRequest';

export interface UpdateSubscriptionSplitRequest {
  /** Defines if the split is enabled */
  enabled: boolean;
  /** Split */
  rules: CreateSplitRequest[];
}

export const updateSubscriptionSplitRequestSchema: Schema<UpdateSubscriptionSplitRequest> = object(
  {
    enabled: ['enabled', boolean()],
    rules: ['rules', array(lazy(() => createSplitRequestSchema))],
  }
);
