/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface UpdateSubscriptionDueDaysRequest {
  boletoDueDays: number;
}

export const updateSubscriptionDueDaysRequestSchema: Schema<UpdateSubscriptionDueDaysRequest> = object(
  { boletoDueDays: ['boleto_due_days', number()] }
);
