/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

/** Update Order item Request */
export interface UpdateOrderItemRequest {
  amount: number;
  description: string;
  quantity: number;
  category: string;
}

export const updateOrderItemRequestSchema: Schema<UpdateOrderItemRequest> = object(
  {
    amount: ['amount', number()],
    description: ['description', string()],
    quantity: ['quantity', number()],
    category: ['category', string()],
  }
);
