/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, object, optional, Schema, string } from '../schema';
import {
  CreateAddressRequest,
  createAddressRequestSchema,
} from './createAddressRequest';
import {
  CreatePhonesRequest,
  createPhonesRequestSchema,
} from './createPhonesRequest';

/** Request for updating a customer */
export interface UpdateCustomerRequest {
  /** Name */
  name?: string;
  /** Email */
  email?: string;
  /** Document number */
  document?: string;
  /** Person type */
  type?: string;
  /** Address */
  address?: CreateAddressRequest;
  /** Metadata */
  metadata?: Record<string, string>;
  phones?: CreatePhonesRequest;
  /** Código de referência do cliente no sistema da loja. Max: 52 caracteres */
  code?: string;
  /** Gênero do cliente */
  gender?: string;
  documentType?: string;
}

export const updateCustomerRequestSchema: Schema<UpdateCustomerRequest> = object(
  {
    name: ['name', optional(string())],
    email: ['email', optional(string())],
    document: ['document', optional(string())],
    type: ['type', optional(string())],
    address: ['address', optional(lazy(() => createAddressRequestSchema))],
    metadata: ['metadata', optional(dict(string()))],
    phones: ['phones', optional(lazy(() => createPhonesRequestSchema))],
    code: ['code', optional(string())],
    gender: ['gender', optional(string())],
    documentType: ['document_type', optional(string())],
  }
);
