/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  CreateCardRequest,
  createCardRequestSchema,
} from './createCardRequest';

/** Request for updating the card from a subscription */
export interface UpdateSubscriptionCardRequest {
  /** Credit card data */
  card: CreateCardRequest;
  /** Credit card id */
  cardId: string;
  /** Business model identifier */
  indirectAcceptor?: string;
}

export const updateSubscriptionCardRequestSchema: Schema<UpdateSubscriptionCardRequest> = object(
  {
    card: ['card', lazy(() => createCardRequestSchema)],
    cardId: ['card_id', string()],
    indirectAcceptor: ['indirect_acceptor', optional(string())],
  }
);
