/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Request for updating the due date from a subscription */
export interface UpdateSubscriptionBillingDateRequest {
  /** The date when the next subscription billing must occur */
  nextBillingAt: string;
}

export const updateSubscriptionBillingDateRequestSchema: Schema<UpdateSubscriptionBillingDateRequest> = object(
  { nextBillingAt: ['next_billing_at', string()] }
);
