/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Request for updating the start date from a subscription */
export interface UpdateSubscriptionStartAtRequest {
  /** The date when the subscription periods will start */
  startAt: string;
}

export const updateSubscriptionStartAtRequestSchema: Schema<UpdateSubscriptionStartAtRequest> = object(
  { startAt: ['start_at', string()] }
);
