/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface UpdateOrderStatusRequest {
  /** Order status */
  status: string;
}

export const updateOrderStatusRequestSchema: Schema<UpdateOrderStatusRequest> = object(
  { status: ['status', string()] }
);
