/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface UpdateTransferSettingsRequest {
  transferEnabled: string;
  transferInterval: string;
  transferDay: string;
}

export const updateTransferSettingsRequestSchema: Schema<UpdateTransferSettingsRequest> = object(
  {
    transferEnabled: ['transfer_enabled', string()],
    transferInterval: ['transfer_interval', string()],
    transferDay: ['transfer_day', string()],
  }
);
