/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

/** Request for updating a price bracket */
export interface UpdatePriceBracketRequest {
  /** Start quantity of the bracket */
  startQuantity: number;
  /** Price */
  price: number;
  /** End quantity of the bracket */
  endQuantity?: number;
  /** Overage price */
  overagePrice?: number;
}

export const updatePriceBracketRequestSchema: Schema<UpdatePriceBracketRequest> = object(
  {
    startQuantity: ['start_quantity', number()],
    price: ['price', number()],
    endQuantity: ['end_quantity', optional(number())],
    overagePrice: ['overage_price', optional(number())],
  }
);
