/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, Schema, string } from '../schema';

/** Request for updating a Recipient */
export interface UpdateRecipientRequest {
  /** Name */
  name: string;
  /** Email */
  email: string;
  /** Description */
  description: string;
  /** Type */
  type: string;
  /** Status */
  status: string;
  /** Metadata */
  metadata: Record<string, string>;
}

export const updateRecipientRequestSchema: Schema<UpdateRecipientRequest> = object(
  {
    name: ['name', string()],
    email: ['email', string()],
    description: ['description', string()],
    type: ['type', string()],
    status: ['status', string()],
    metadata: ['metadata', dict(string())],
  }
);
