/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema.js';
import {
  CreateCardRequest,
  createCardRequestSchema,
} from './createCardRequest.js';
import {
  CreateSubscriptionBoletoRequest,
  createSubscriptionBoletoRequestSchema,
} from './createSubscriptionBoletoRequest.js';

/** Request for updating a subscription's payment method */
export interface UpdateSubscriptionPaymentMethodRequest {
  /** The new payment method */
  paymentMethod: string;
  /** Card id */
  cardId: string;
  /** Card data */
  card: CreateCardRequest;
  /** The Card Token */
  cardToken?: string;
  /** Information about fines and interest on the "boleto" used from payment */
  boleto?: CreateSubscriptionBoletoRequest;
  /** Business model identifier */
  indirectAcceptor?: string | null;
}

export const updateSubscriptionPaymentMethodRequestSchema: Schema<UpdateSubscriptionPaymentMethodRequest> = lazy(
  () =>
    object({
      paymentMethod: ['payment_method', string()],
      cardId: ['card_id', string()],
      card: ['card', createCardRequestSchema],
      cardToken: ['card_token', optional(string())],
      boleto: ['boleto', optional(createSubscriptionBoletoRequestSchema)],
      indirectAcceptor: ['indirect_acceptor', optional(nullable(string()))],
    })
);
