/**
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { passThroughInterceptor } from './core';
import { AuthenticatorInterface } from './core';

/** None authentication provider */
export const noneAuthenticationProvider = () => passThroughInterceptor;

export const basicAuthAuthenticationProvider = ({
  basicAuthUserName,
  basicAuthPassword,
}: {
  basicAuthUserName: string;
  basicAuthPassword: string;
}): AuthenticatorInterface<boolean> => {
  return (requiresAuth?: boolean) => {
    if (!requiresAuth) {
      return passThroughInterceptor;
    }

    return (request, options, next) => {
      request.auth = {
        username: basicAuthUserName,
        password: basicAuthPassword,
      };

      return next(request, options);
    };
  };
};
